
import os

def get_html_ch62():
    return """<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Capítulo LXII: El Libro del Karma</title>
    <link rel="stylesheet" href="../../shared/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&family=EB+Garamond:ital,wght@0,400;0,700;1,400&family=Inter:wght@300;400;500&display=swap" rel="stylesheet">
</head>

<body class="lang-es">
    <div class="scroll-progress"></div>
    <div class="sidebar-overlay"></div>

    <aside class="sidebar">
        <div class="sidebar-header">
            <a href="../../index.html" class="logo-link"><div class="sidebar-logo">KARMA</div></a>
            <button class="toggle-btn">☰</button>
        </div>
        <nav class="sidebar-nav"></nav>
        <div class="sidebar-footer">© Karma 2026</div>
    </aside>

    <main class="main-content">
        <div class="top-header-controls">
            <a href="../../index.html" class="library-quick-link"></a>
            <div class="lang-selector-elegant">
                <button class="lang-current-trigger"><span class="flag">🇪🇸</span> <span class="es">Castellano</span></button>
                <div class="lang-dropdown-menu">
                    <div class="lang-opt" data-lang="es" onclick="setLanguage('es')"><span class="flag">🇪🇸</span> Castellano</div>
                    <div class="lang-opt" data-lang="en" onclick="setLanguage('en')"><span class="flag">🇬🇧</span> English</div>
                    <div class="lang-opt" data-lang="it" onclick="setLanguage('it')"><span class="flag">🇮🇹</span> Italiano</div>
                    <div class="lang-opt" data-lang="zh" onclick="setLanguage('zh')"><span class="flag">🇨🇳</span> 中文</div>
                    <div class="lang-opt" data-lang="ar" onclick="setLanguage('ar')"><span class="flag">🇦🇪</span> العربية</div>
                    <div class="lang-opt" data-lang="ru" onclick="setLanguage('ru')"><span class="flag">🇷🇺</span> Русский</div>
                    <div class="lang-opt" data-lang="de" onclick="setLanguage('de')"><span class="flag">🇩🇪</span> Deutsch</div>
                    <div class="lang-opt" data-lang="fr" onclick="setLanguage('fr')"><span class="flag">🇫🇷</span> Français</div>
                    <div class="lang-opt" data-lang="ja" onclick="setLanguage('ja')"><span class="flag">🇯🇵</span> 日本語</div>
                    <div class="lang-opt" data-lang="pt" onclick="setLanguage('pt')"><span class="flag">🇵🇹</span> Português</div>
                    <div class="lang-opt" data-lang="vi" onclick="setLanguage('vi')"><span class="flag">🇻🇳</span> Tiếng Việt</div>
                </div>
            </div>
            <a class="top-linktree-subtle" href="../../linktree.html">LINKTREE</a>
        </div>

        <header class="mobile-header">
            <button class="toggle-btn">☰</button>
            <div class="sidebar-logo">KARMA</div>
        </header>

        <section class="hero-section">
            <img src="assets/hero.jpg" alt="Karma LXII" id="hero-img">
            <div class="hero-overlay"></div>
            <div class="hero-content">
                <div class="chapter-num">
                    <span class="es">CAPÍTULO LXII</span><span class="en">CHAPTER LXII</span><span class="it">CAPITOLO LXII</span><span class="zh">第六十二章</span><span class="ar">الفصل الثاني والستون</span><span class="ru">ГЛАВА LXII</span><span class="de">KAPITEL LXII</span><span class="fr">CHAPITRE LXII</span><span class="ja">第62章</span><span class="pt">CAPÍTULO LXII</span><span class="vi">CHƯƠNG LXII</span>
                </div>
                <h1 class="chapter-title">
                    <span class="es">El Veneno de la Limosna Arrogante</span>
                    <span class="en">The Poison of Arrogant Alms</span>
                    <span class="it">Il Veleno dell'Elemosina Arrogante</span>
                    <span class="zh">傲慢施舍之毒</span>
                    <span class="ar">سم الصدقة المتكبرة</span>
                    <span class="ru">Яд высокомерной милостыни</span>
                    <span class="de">Das Gift des hochmütigen Almosens</span>
                    <span class="fr">Le Poison de l'Aumône Arrogante</span>
                    <span class="ja">傲慢な施しの毒</span>
                    <span class="pt">O Veneno da Esmola Arrogante</span>
                    <span class="vi">Chất Độc Của Sự Bố Thí Kiêu Ngạo</span>
                </h1>
                <p class="subtitle">
                    <span class="es">"La mano que da para humillar, no está soltando el oro, sino comprando su propia soledad; lo que das con burla, te será devuelto en el eco de las risas de quienes te rodean."</span>
                    <span class="en">"The hand that gives to humiliate is not releasing gold, but buying its own loneliness; what you give with mockery will be returned to you in the echo of the laughter of those around you."</span>
                    <span class="it">"La mano che dà per umiliare non sta lasciando l'oro, ma comprando la propria solitudine; ciò che dai con scherno ti tornerà nell'eco delle risate di chi ti circonda."</span>
                    <span class="zh">“为了羞辱而施予的手，放下的不是黄金，而是购买了自己的孤独；你带着嘲弄给予的一切，都将在周围人的笑声回响中还给你。”</span>
                    <span class="ar">"اليد التي تعطي للإذلال لا تطلق الذهب، بل تشتري وحدتها الخاصة؛ وما تعطيه بسخرية سيعود إليك في صدى ضحكات من حولك."</span>
                    <span class="ru">«Рука, дающая ради унижения, не выпускает золото, а покупает собственное одиночество; то, что ты даешь с насмешкой, вернется к тебе эхом смеха окружающих».</span>
                    <span class="de">„Die Hand, die gibt, um zu demütigen, lässt nicht Gold los, sondern kauft ihre eigene Einsamkeit; was du mit Spott gebst, wird dir im Echo des Lachens derer um dich herum zurückgegeben.“</span>
                    <span class="fr">« La main qui donne pour humilier ne lâche pas l'or, mais achète sa propre solitude ; ce que tu donnes avec dérision te sera rendu dans l'écho des rires de ceux qui t'entourent. »</span>
                    <span class="ja">「屈辱を与えるために差し出される手は、黄金を放しているのではなく、自らの孤独を買っているのです。嘲笑とともに与えたものは、周囲の人々の笑い声の響きとなってあなたに返ってくるでしょう。」</span>
                    <span class="pt">"A mão que dá para humilhar não está a soltar o ouro, mas a comprar a sua própria solidão; o que dás com deboche ser-te-á devolvido no eco dos risos de quem te rodeia."</span>
                    <span class="vi">"Bàn tay cho đi để nhục mạ không phải đang buông bỏ vàng bạc, mà là đang mua lấy sự cô độc của chính mình; những gì bạn cho đi với sự chế nhạo sẽ quay lại với bạn trong tiếng cười nhạo báng của những kẻ xung quanh."</span>
                </p>
                <div class="scroll-indicator"></div>
            </div>
        </section>

        <div class="story-container">
            <!-- ═══ EXPLICACIÓN KÁRMICA ═══ -->
            <div class="story-block fade-in">
                <!-- ES -->
                <p class="es"><span class="drop-cap">E</span>l karma es un espejo de una precisión aterradora, no solo registra lo que hacemos, sino la frecuencia emocional desde la que actuamos. El acto de dar, la generosidad, es en esencia una apertura del corazón, una expansión del alma hacia el otro. Sin embargo, cuando esa generosidad se contamina con la soberbia, el resultado kármico se fragmenta. El universo reconoce el flujo de la riqueza y te devuelve abundancia material, pero también registra la humillación que infligiste. El resultado es una paradoja dolorosa: una vida llena de recursos pero vacía de respeto genuino.</p>
                <p class="es">Este mecanismo funciona porque el desprecio que lanzas al dar es una declaración de superioridad ilusoria. Al burlarte de quien recibe, estás sembrando la semilla de tu propio aislamiento. En el futuro, tu fortuna será como un banquete en una sala llena de espejos deformantes: verás gente a tu alrededor, disfrutarás de los mejores manjares, pero percibirás que nadie te mira con amor, sino con la misma mirada de mofa que tú regalaste un día. Estar rodeado de personas que se ríen de ti a tus espaldas es el eco exacto del desprecio que sembraste bajo el disfraz de la caridad.</p>
                <p class="es">El "antes" de este karma es la ceguera del ego, que cree que el dinero le da derecho a pisotear la dignidad ajena. El "después" es la riqueza amarga, donde el dinero no puede comprar un solo gramo de lealtad o afecto real. Para alinear nuestra vida con el Ikigai luminoso, debemos entender que el respeto es el recipiente que contiene la bendición de la abundancia. Sin respeto, la riqueza es solo un adorno en una celda de soledad. Dar con humildad es la única forma de asegurar que nuestra cosecha futura sea dulce y esté habitada por la luz de la verdadera compañía.</p>

                <!-- EN -->
                <p class="en"><span class="drop-cap">K</span>arma is a mirror of terrifying precision; it records not only what we do, but the emotional frequency from which we act. The act of giving, of generosity, is essentially an opening of the heart, an expansion of the soul toward another. However, when that generosity is contaminated with pride, the karmic result fragments. The universe recognizes the flow of wealth and returns material abundance to you, but it also records the humiliation you inflicted. The result is a painful paradox: a life full of resources but empty of genuine respect.</p>
                <p class="en">This mechanism works because the contempt you throw when giving is a declaration of illusory superiority. By mocking the recipient, you are sowing the seed of your own isolation. In the future, your fortune will be like a banquet in a room full of distorting mirrors: you will see people around you, you will enjoy the finest delicacies, but you will perceive that no one looks at you with love, but with the same mocking gaze you once gave. Being surrounded by people who laugh at you behind your back is the exact echo of the contempt you sowed under the guise of charity.</p>
                <p class="en">The "before" of this karma is the blindness of the ego, which believes that money gives it the right to trample on the dignity of others. The "after" is bitter wealth, where money cannot buy a single gram of loyalty or real affection. To align our lives with the luminous Ikigai, we must understand that respect is the vessel that contains the blessing of abundance. Without respect, wealth is just an ornament in a cell of loneliness. Giving with humility is the only way to ensure that our future harvest is sweet and inhabited by the light of true companionship.</p>

                <!-- IT -->
                <p class="it"><span class="drop-cap">I</span>l karma è uno specchio di una precisione terrificante; registra non solo ciò che facciamo, ma la frequenza emotiva da cui agiamo. L'atto del dare, la generosità, è in essenza un'apertura del cuore, un'espansione dell'anima verso l'altro. Tuttavia, quando quella generosità è contaminata dalla superbia, il risultato karmico si frammenta. L'universo riconosce il flusso della ricchezza e ti restituisce abbondanza materiale, ma registra anche l'umiliazione che hai inflitto. Il risultato è un paradosso doloroso: una vita piena di risorse ma vuota di rispetto genuino.</p>
                <p class="it">Questo meccanismo funziona perché il disprezzo che lanci nel dare è una dichiarazione di illusoria superiorità. Deridendo chi riceve, stai seminando il seme del tuo stesso isolamento. In futuro, la tua fortuna sarà come un banchetto in una sala piena di specchi deformanti: vedrai persone intorno a te, godrai dei migliori piatti, ma percepirai che nessuno ti guarda con amore, ma con lo stesso sguardo di scherno che tu hai regalato un giorno. Essere circondato da persone che ridono di te alle tue spalle è l'eco esatta del disprezzo che hai seminato sotto le spoglie della carità.</p>
                <p class="it">Il "prima" di questo karma è la cecità dell'ego, che crede che il denaro gli dia il diritto di calpestare la dignità altrui. Il "dopo" è la ricchezza amarga, dove il denaro non può comprare un solo grammo di lealtà o di affetto reale. Per allineare la nostra vita con l'Ikigai luminoso, dobbiamo capire che il rispetto è il recipiente che contiene la benedizione dell'abbondanza. Senza rispetto, la ricchezza è solo un ornamento in una cella di solitudine. Dare con umiltà è l'unico modo per assicurare che il nostro futuro raccolto sia dolce e abitato dalla luce della vera compagnia.</p>

                <!-- ZH -->
                <p class="zh"><span class="drop-cap">业</span>力是一面精确得令人畏惧的镜子，它记录的不仅是我们的所作所为，还有我们行动时的情感频率。施予的行为，即慷慨，本质上是心灵的开启，是灵魂向他人的扩张。然而，当这种慷慨被傲慢污染时，业力的结果就会破碎。宇宙认可财富的流动，并回报你物质上的富足，但它也记录了你施加的羞辱。结果是一个痛苦的悖论：生活资源充足，却缺乏真诚的尊重。</p>
                <p class="zh">这种机制之所以起作用，是因为你在施予时抛出的轻蔑是一种虚幻优越感的宣言。通过嘲弄接受者，你正在播下自己孤立的种子。在未来，你的财富将像一场充满变形镜的宴会：你会看到周围有人，你会享受最好的美食，但你会感觉到没有人带着爱看着你，而是带着你曾经给予过的同样的嘲笑目光。被在背后嘲笑你的人包围，正是你在慈善伪装下播下的轻蔑的准确回响。</p>
                <p class="zh">这种业力的“前因”是自我的盲目，认为金钱赋予了其践踏他人尊严的权利。而“后果”则是苦涩的财富，金钱买不到哪怕一克的忠诚或真正的感情。为了让我们的生活与光明的伊基盖（Ikigai）保持一致，我们必须明白，尊重是装载丰盛祝福的容器。没有尊重，财富只是孤独牢房中的装饰品。以谦卑施予是确保我们未来的收获是甜蜜的，并充满真诚陪伴之光的唯一途径。</p>

                <!-- AR -->
                <p class="ar"><span class="drop-cap">ا</span>لكارما هي مرآة ذات دقة مرعبة، فهي لا تسجل ما نفعله فحسب، بل تسجل التردد العاطفي الذي نتصرف من خلاله. فعل العطاء، أي الكرم، هو في جوهره انفتاح للقلب، وتوسع للروح تجاه الآخر. ومع ذلك، عندما يتلوث هذا الكرم بالغطرسة، تتهشم النتيجة الكارمية. يتعرف الكون على تدفق الثروة ويعيد لك الوفرة المادية، لكنه يسجل أيضاً الإذلال الذي ألحقته. والنتيجة هي مفارقة مؤلمة: حياة مليئة بالموارد ولكنها خالية من الاحترام الحقيقي.</p>
                <p class="ar">تعمل هذه الآلية لأن الازدراء الذي تظهره عند العطاء هو إعلان عن تفوق وهمي. من خلال السخرية من المتلقي، فإنك تزرع بذور عزلتك الخاصة. في المستقبل، ستكون ثروتك مثل مأدبة في قاعة مليئة بالمرايا المشوهة: سترى أشخاصاً من حولك، وستستمتع بأفضل المأكولات، لكنك ستشعر أنه لا أحد ينظر إليك بحب، بل بنفس نظرة السخرية التي منحتها يوماً ما. إن كونك محاطاً بأشخاص يضحكون عليك وراء ظهرك هو الصدى الدقيق للازدراء الذي زرعته تحت قناع الصدقة.</p>
                <p class="ar">"ما قبل" هذه الكارما هو عمى الأنا، التي تعتقد أن المال يمنحها الحق في دوس كرامة الآخرين. أما "ما بعد" فهو الثروة المرة، حيث لا يمكن للمال شراء غرام واحد من الولاء أو المودة الحقيقية. لكي نوجه حياتنا نحو الـ "إيكيغاي" المضيء، يجب أن نفهم أن الاحترام هو الوعاء الذي يحتوي على بركة الوفرة. بدون احترام، تكون الثروة مجرد زينة في زنزانة من الوحدة. العطاء بتواضع هو الطريقة الوحيدة لضمان أن يكون حصادنا المستقبلي حلواً ومسكوناً بنور الرفقة الحقيقية.</p>

                <!-- RU -->
                <p class="ru"><span class="drop-cap">К</span>арма — это зеркало пугающей точности, оно фиксирует не только то, что мы делаем, но и эмоциональную частоту, на которой мы действуем. Акт даяния, щедрость, по сути, является открытием сердца, расширением души навстречу другому. Однако когда эта щедрость осквернена гордыней, кармический результат фрагментируется. Вселенная признает поток богатства и возвращает вам материальное изобилие, но она также фиксирует унижение, которое вы нанесли. Результат — болезненный парадокс: жизнь, полная ресурсов, но лишенная подлинного уважения.</p>
                <p class="ru">Этот механизм работает потому, что презрение, которое вы проявляете при даянии, является заявлением об иллюзорном превосходстве. Издеваясь над получателем, вы сеете семена собственной изоляции. В будущем ваше состояние будет подобно банкету в зале, полном кривых зеркал: вы будете видеть людей вокруг себя, наслаждаться лучшими яствами, но будете чувствовать, что никто не смотрит на вас с любовью, а лишь с тем же насмешливым взглядом, который вы когда-то подарили другим. Оказаться в окружении людей, которые смеются над вами за вашей спиной — это точное эхо того презрения, которое вы посеяли под маской благотворительности.</p>
                <p class="ru">Состояние «до» этой кармы — это слепота эго, верящего, что деньги дают ему право попирать чужое достоинство. «После» — это горькое богатство, где на деньги нельзя купить ни грамма верности или настоящей привязанности. Чтобы привести нашу жизнь в соответствие со светлым Икигай, мы должны понимать, что уважение — это сосуд, в котором содержится благословение изобилия. Без уважения богатство — лишь украшение в камере одиночества. Даяние со смирением — единственный способ гарантировать, что наш будущий урожай будет сладким и наполненным светом истинной дружбы.</p>

                <!-- DE -->
                <p class="de"><span class="drop-cap">K</span>arma ist ein Spiegel von erschreckender Präzision; es registriert nicht nur, was wir tun, sondern auch die emotionale Frequenz, aus der heraus wir handeln. Der Akt des Gebens, die Großzügigkeit, ist im Wesentlichen eine Öffnung des Herzens, eine Ausdehnung der Seele auf den anderen zu. Wenn diese Großzügigkeit jedoch durch Hochmut verunreinigt wird, zerfällt das karmische Ergebnis. Das Universum erkennt den Fluss des Reichtums an und gibt dir materiellen Überfluss zurück, aber es registriert auch die Demütigung, die du zugefügt hast. Das Ergebnis ist ein schmerzhaftes Paradoxon: ein Leben voller Ressourcen, aber leer an echtem Respekt.</p>
                <p class="de">Dieser Mechanismus funktioniert, weil die Verachtung, die du beim Geben ausstrahlst, eine Erklärung illusorischer Überlegenheit ist. Indem du dich über den Empfänger lustig machst, säst du den Samen deiner eigenen Isolation. In Zukunft wird dein Glück wie ein Bankett in einem Saal voller Zerrspiegel sein: Du wirst Menschen um dich herum sehen, du wirst die besten Speisen genießen, aber du wirst spüren, dass dich niemand mit Liebe ansieht, sondern mit demselben spöttischen Blick, den du einst verschenkt hast. Von Menschen umgeben zu sein, die hinter deinem Rücken über dich lachen, ist das exakte Echo der Verachtung, die du unter dem Deckmantel der Wohltätigkeit gesät hast.</p>
                <p class="de">Das „Vorher“ dieses Karmas ist die Blindheit des Egos, das glaubt, Geld gäbe ihm das Recht, die Würde anderer mit Füßen zu treten. Das „Nachher“ ist bitterer Reichtum, in dem Geld kein Gramm Loyalität oder echte Zuneigung kaufen kann. Um unser Leben mit dem leuchtenden Ikigai in Einklang zu bringen, weissen wir verstehen, dass Respekt das Gefäß ist, das den Segen des Überflusses enthält. Ohne Respekt ist Reichtum nur ein Schmuck in einer Zelle der Einsamkeit. Mit Demut zu geben ist der einzige Weg, um sicherzustellen, dass unsere künftige Ernte süß und vom Licht wahrer Gemeinschaft erfüllt ist.</p>

                <!-- FR -->
                <p class="fr"><span class="drop-cap">L</span>e karma est un miroir d'une précision terrifiante ; il enregistre non seulement ce que nous faisons, mais aussi la fréquence émotionnelle depuis laquelle nous agissons. L'acte de donner, la générosité, est par essence une ouverture du cœur, une expansion de l'âme vers l'autre. Cependant, quand cette générosité est contaminée par l'orgueil, le résultat karmique se fragmente. L'univers reconnaît le flux de la richesse et vous rend l'abondance matérielle, mais il enregistre aussi l'humiliation que vous avez infligée. Le résultat est un paradoxe douloureux : une vie pleine de ressources mais vide de respect sincère.</p>
                <p class="fr">Ce mécanisme fonctionne parce que le mépris que vous lancez en donnant est une déclaration de supériorité illusoire. En vous moquant de celui qui reçoit, vous semez la graine de votre propre isolement. À l'avenir, votre fortune sera comme un banquet dans une salle pleine de miroirs déformants : vous verrez des gens autour de vous, vous profiterez des meilleurs mets, mais vous percevrez que personne ne vous regarde avec amour, mais avec le même regard moqueur que vous avez offert un jour. Être entouré de gens qui rient de vous dans votre dos est l'écho exact du mépris que vous avez semé sous le déguisement de la charité.</p>
                <p class="fr">Le « avant » de ce karma est l'aveuglement de l'ego, qui croit que l'argent lui donne le droit de bafouer la dignité d'autrui. Le « après » est la richesse amère, où l'argent ne peut acheter un seul gramme de loyauté ou d'affection réelle. Pour aligner notre vie avec l'Ikigai lumineux, nous devons comprendre que le respect est le récipient qui contient la bénédiction de l'abondance. Sans respect, la richesse n'est qu'un ornement dans une cellule de solitude. Donner avec humilité est le seul moyen de s'assurer que notre récolte future sera douce et habitée par la lumière d'une véritable compagnie.</p>

                <!-- JA -->
                <p class="ja"><span class="drop-cap">カ</span>ルマは恐ろしいほど精密な鏡です。それは私たちが何をなすかだけでなく、どのような感情の周波数から行動しているかを記録します。与えるという行為、すなわち寛大さは、本質的に心の開放であり、他者への魂の拡張です。しかし、その寛大さが傲慢さによって汚染されるとき、カルマの結果は断片化されます。宇宙は富の流れを認識し、物質的な豊かさを返しますが、同時にあなたが与えた屈辱も記録します。その結果、資源には満ちているが真の尊敬を欠いた、痛ましいパラドックスが生じます。</p>
                <p class="ja">このメカニズムが働くのは、与えるときに発せられる軽蔑が、幻想的な優越感の宣言だからです。受け取る側を嘲笑うことで、あなたは自らの孤立の種をまいているのです。将来、あなたの幸運は、歪んだ鏡でいっぱいの部屋での宴会のようになるでしょう。周囲に人々が見え、最高の馳走を楽しみますが、誰もあなたを愛の目で見ているのではなく、かつてあなたが与えたのと同じ嘲笑の目で見ていることに気づくでしょう。背後で笑う人々に囲まれることは、慈善の仮面の下でまいた軽蔑の正確な反響なのです。</p>
                <p class="ja">このカルマの「前」は、金があれば他人の尊厳を踏みにじる権利があると思い込むエゴの盲目です。「後」は苦い富であり、金では一グラムの忠誠も真の愛情も買うことはできません。私たちの人生を輝かしい生きがい（Ikigai）に合わせるためには、尊敬こそが豊かさの祝福を収める器であることを理解しなければなりません。尊敬がなければ、富は孤独の独房の中の装飾にすぎません。謙虚に与えることこそが、将来の収穫を甘美なものにし、真の仲間の光に満ちたものにする唯一の方法なのです。</p>

                <!-- PT -->
                <p class="pt"><span class="drop-cap">O</span> karma é um espelho de uma precisão aterradora, não só regista o que fazemos, mas a frequência emocional a partir da qual agimos. O ato de dar, la generosidad, é em essência uma abertura do coração, uma expansão da alma em direção ao outro. No entanto, quando essa generosidade se contamina com a soberba, o resultado kármico fragmenta-se. O universo reconhece o fluxo da riqueza e devolve-te abundância material, pero também regista a humilhação que infligiste. O resultado é un paradoxo doloroso: uma vida cheia de recursos mas vazia de respeito genuíno.</p>
                <p class="pt">Este mecanismo funciona porque o desprezo que lanças ao dar é uma declaração de superioridade ilusória. Ao burlares-te de quem recebe, estás a semear a semente do teu próprio isolamento. No futuro, a tua fortuna será como um banquete numa sala cheia de espelhos deformantes: verás pessoas ao teu redor, desfrutarás dos melhores manjares, mas perceberás que ninguém te olha com amor, mas com o mesmo olhar de mofa que tu regalaste un día. Estar rodeado de pessoas que se riem de ti pelas tuas costas é o eco exato do desprezo que semeaste sob o disfarce da caridad.</p>
                <p class="pt">O "antes" deste karma é a cegueira do ego, que acredita que o dinheiro lhe dá o direito de pisotear a dignidade alheia. O "depois" é a riqueza amarga, onde o dinheiro não pode comprar um único grama de lealdade ou afeto real. Para alinhar a nossa vida com o Ikigai luminoso, debemos entender que o respeito é o recipiente que contém a bênção da abundância. Sem respeito, a riqueza é apenas un adorno numa cela de solidão. Dar com humildade é a única forma de assegurar que a nossa colheita futura seja doce e esteja habitada pela luz da verdadeira companhia.</p>

                <!-- VI -->
                <p class="vi"><span class="drop-cap">N</span>hân quả là một tấm gương có độ chính xác đáng sợ, nó không chỉ ghi lại những gì chúng ta làm mà cả tần số cảm xúc mà chúng ta hành động từ đó. Hành động cho đi, lòng hào phóng, về bản chất là sự mở rộng của trái tim, sự mở mang của linh hồn hướng về người khác. Tuy nhiên, khi lòng hào phóng đó bị vấy bẩn bởi sự kiêu ngạo, kết quả nhân quả sẽ bị phân mảnh. Vũ trụ công nhận dòng chảy của sự giàu có và trả lại cho bạn sự phong phú về vật chất, nhưng nó cũng ghi lại sự sỉ nhục mà bạn đã gây ra. Kết quả là một nghịch lý đau đớn: một cuộc sống đầy rẫy nguồn lực nhưng lại trống rỗng sự tôn trọng chân thành.</p>
                <p class="vi">Cơ chế này hoạt động vì sự khinh miệt mà bạn tung ra khi cho đi là một tuyên bố về sự ưu việt ảo tưởng. Bằng cách chế nhạo người nhận, bạn đang gieo hạt giống cho sự cô lập của chính mình. Trong tương lai, vận may của bạn sẽ giống như một bữa tiệc trong một căn phòng đầy gương biến dạng: bạn sẽ thấy mọi người xung quanh mình, bạn sẽ thưởng thức những món ăn ngon nhất, nhưng bạn sẽ nhận ra rằng không ai nhìn bạn bằng tình yêu, mà bằng chính ánh mắt chế nhạo mà bạn đã từng dành cho người khác. Việc bị vây quanh bởi những người cười nhạo sau lưng bạn chính là tiếng vang chính xác của sự khinh miệt mà bạn đã gieo dưới vỏ bọc của lòng từ thiện.</p>
                <p class="vi">Cái "trước" của nghiệp này là sự mù quáng của bản ngã, kẻ tin rằng tiền bạc cho hắn quyền chà đạp lên nhân phẩm của người khác. Cái "sau" là sự giàu có cay đắng, nơi tiền bạc không thể mua được dù chỉ một gam lòng trung thành hay tình cảm thực sự. Để điều chỉnh cuộc sống của chúng ta theo Ikigai tươi sáng, chúng ta phải hiểu rằng sự tôn trọng là chiếc bình chứa đựng phước lành của sự phong phú. Không có sự tôn trọng, giàu sang chỉ là vật trang trí trong ngục tù đơn độc. Cho đi với sự khiêm nhường là cách duy nhất để đảm bảo rằng mùa gặt tương lai của chúng ta sẽ ngọt ngào và tràn đầy ánh sáng của sự đồng hành thực sự.</p>
            </div>

            <!-- ═══ PARÁBOLA ═══ -->
            <div class="story-block parable-block fade-in" style="margin-top: 3rem; margin-bottom: 2rem; padding: 0 1rem;">
                <h3 class="es" style="color: var(--gold); text-align: center; font-family: 'Cinzel', serif; margin-bottom: 2rem;">El Banquete de las Risas Huecas</h3>
                <h3 class="en" style="color: var(--gold); text-align: center; font-family: 'Cinzel', serif; margin-bottom: 2rem;">The Banquet of Hollow Laughter</h3>
                <h3 class="it" style="color: var(--gold); text-align: center; font-family: 'Cinzel', serif; margin-bottom: 2rem;">Il Banchetto delle Risate Vuote</h3>
                <h3 class="zh" style="color: var(--gold); text-align: center; font-family: 'Cinzel', serif; margin-bottom: 2rem;">空洞笑声之宴</h3>
                <h3 class="ar" style="color: var(--gold); text-align: center; font-family: 'Cinzel', serif; margin-bottom: 2rem;">مأدبة الضحكات الجوفاء</h3>
                <h3 class="ru" style="color: var(--gold); text-align: center; font-family: 'Cinzel', serif; margin-bottom: 2rem;">Пир пустых насмешек</h3>
                <h3 class="de" style="color: var(--gold); text-align: center; font-family: 'Cinzel', serif; margin-bottom: 2rem;">Das Bankett des hohlen Lachens</h3>
                <h3 class="fr" style="color: var(--gold); text-align: center; font-family: 'Cinzel', serif; margin-bottom: 2rem;">Le Banquet des Rires Creux</h3>
                <h3 class="ja" style="color: var(--gold); text-align: center; font-family: 'Cinzel', serif; margin-bottom: 2rem;">虚ろな笑いの宴</h3>
                <h3 class="pt" style="color: var(--gold); text-align: center; font-family: 'Cinzel', serif; margin-bottom: 2rem;">O Banquete dos Risos Vazios</h3>
                <h3 class="vi" style="color: var(--gold); text-align: center; font-family: 'Cinzel', serif; margin-bottom: 2rem;">Bữa Tiệc Của Những Tiếng Cười Rỗng Tuếch</h3>

                <!-- ES -->
                <p class="es" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">En la antigua ciudad de Benarés, vivía un joven rico llamado Vimal que se jactaba de su gran generosidad. Vimal solía salir a las plazas y, con gesto altivo, lanzaba monedas de oro a los mendigos, disfrutando de ver cómo se peleaban por ellas. "¡Mirad cómo se arrastran por mi brillo!", decía entre risas a sus amigos, mientras señalaba las cicatrices y los harapos de los necesitados. Daba mucho, pero cada moneda iba acompañada de un chiste cruel o una mirada de profundo asco. Creía que su riqueza le otorgaba un trono de superioridad desde el cual podía juzgar la desdicha ajena.</p>
                <p class="es" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Los años pasaron y, tal como dicta el karma, la generosidad de Vimal le trajo aún más riquezas. Se convirtió en el hombre más próspero de la región, dueño de palacios que deslumbraban al sol. Sin embargo, algo extraño empezó a suceder en su círculo social. Vimal organizaba fiestas legendarias, gastando fortunas en los mejores músicos y vinos, pero pronto se dio cuenta de que el ambiente era gélido. Notaba cómo, en el momento en que él entraba en una sala, los murmullos se detenían, y en cuanto se daba la vuelta, el aire se llenaba de risas disimuladas. Sus "amigos" comían de su mesa, pero sus ojos brillaban con la misma burla que él había mostrado antaño.</p>
                <p class="es" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Un día, Vimal escuchó a su invitado más cercano decir: "Es patético, cree que su oro oculta lo ridículo que se ve intentando comprar nuestra admiración. Es solo un tonto con monedas". En ese instante, Vimal recordó la cara del niño mendigo al que le había lanzado una moneda mientras se reía de su orfandad. Comprendió que había construido un palacio de oro, pero que el cemento eran las burlas que había sembrado. Tenía todo lo que el dinero podía comprar, excepto lo único que su alma necesitaba: el respeto sincero de otro ser humano.</p>
                <p class="es" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Vimal pasó el resto de sus días en el silencio de sus salones vacíos, dándose cuenta de que la verdadera caridad no es dar lo que te sobra, sino reconocer tu propia fragilidad en el otro. Su Ikigai se había oscurecido porque había olvidado que la riqueza sin honor es una corona de espinas doradas. Su historia nos enseña que el karma no se equivoca de dirección: si siembras monedas con espinas de desprecio, recogerás una montaña de oro, pero te pincharás con cada pieza al intentar abrazar a alguien.</p>

                <!-- EN -->
                <p class="en" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">In the ancient city of Varanasi, lived a wealthy young man named Vimal who boasted of his great generosity. Vimal used to go out to the squares and, with a haughty gesture, throw gold coins to the beggars, enjoying seeing them fight over them. "Look how they crawl for my shine!" he would say with a laugh to his friends, while pointing at the scars and rags of the needy. He gave a lot, but every coin was accompanied by a cruel joke or a look of profound disgust. He believed that his wealth gave him a throne of superiority from which he could judge the misfortune of others.</p>
                <p class="en" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Years passed and, as karma dictates, Vimal's generosity brought him even more wealth. He became the most prosperous man in the region, owner of palaces that dazzled in the sun. However, something strange began to happen in his social circle. Vimal organized legendary parties, spending fortunes on the best musicians and wines, but he soon realized that the atmosphere was icy. He noticed how, the moment he entered a room, the murmurs stopped, and as soon as he turned around, the air was filled with disguised laughter. His "friends" ate from his table, but their eyes shone with the same mockery he had shown in the past.</p>
                <p class="en" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">One day, Vimal heard his closest guest say: "It's pathetic; he thinks his gold hides how ridiculous he looks trying to buy our admiration. He's just a fool with coins." At that moment, Vimal remembered the face of the beggar child to whom he had thrown a coin while laughing at his orphanhood. He understood that he had built a palace of gold, but the cement was the mockery he had sown. He had everything money could buy, except the only thing his soul needed: the sincere respect of another human being.</p>
                <p class="en" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Vimal spent the rest of his days in the silence of his empty halls, realizing that true charity is not giving what you have left over, but recognizing your own fragility in the other. His Ikigai had darkened because he had forgotten that wealth without honor is a crown of golden thorns. His story teaches us that karma does not mistake its direction: if you sow coins with thorns of contempt, you will reap a mountain of gold, but you will prick yourself with every piece when trying to embrace someone.</p>

                <!-- IT -->
                <p class="it" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Nell'antica città di Varanasi viveva un giovane ricco di nome Vimal, che si vantava della sua grande generosità. Vimal era solito andare nelle piazze e, con gesto altezzoso, lanciare monete d'oro ai mendicanti, divertendosi a vederli lottare per esse. "Guardate come strisciano per il mio splendore!", diceva ridendo ai suoi amici, indicando le cicatrici e gli stracci dei bisognosi. Dava molto, ma ogni moneta era accompagnata da una battuta crudele o da uno sguardo di profondo disgusto. Credeva che la sua ricchezza gli conferisse un trono di superiorità dal quale poter giudicare la sfortuna altrui.</p>
                <p class="it" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Gli anni passarono e, come detta il karma, la generosità di Vimal gli portò ancora più ricchezze. Divenne l'uomo più prospero della regione, proprietario di palazzi che abbagliavano al sole. Tuttavia, qualcosa di strano iniziò ad accadere nella sua cerchia sociale. Vimal organizzava feste leggendarie, spendendo fortune per i migliori musicisti e vini, ma presto si rese conto che l'atmosfera era gelida. Notava come, nel momento in cui entrava in una sala, i mormorii si interrompevano e, non appena si voltava, l'aria si riempiva di risate soffocate. I suoi "amici" mangiavano alla sua tavola, ma i loro occhi brillavano dello stesso scherno che lui aveva mostrato un tempo.</p>
                <p class="it" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Un giorno Vimal sentì il suo ospite più intimo dire: "È patetico, crede che il suo oro nasconda quanto sia ridicolo mentre cerca di comprare la nostra ammirazione. È solo uno sciocco con le monete". In quel momento Vimal ricordò il volto del bambino mendicante a cui aveva lanciato una moneta ridendo della sua orfanezza. Capì di aver costruito un palazzo d'oro, ma che il cemento erano gli scherni che aveva seminato. Aveva tutto ciò che il denaro poteva comprare, tranne l'unica cosa di cui la sua anima aveva bisogno: il rispetto sincero di un altro essere umano.</p>
                <p class="it" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Vimal passò il resto dei suoi giorni nel silenzio dei suoi saloni vuoti, rendendosi conto che la vera carità non è dare ciò che ti avanza, ma riconoscere la tua fragilità nell'altro. Il suo Ikigai si era oscurato perché aveva dimenticato che la ricchezza senza onore è una corona di spine dorate. La sua storia ci insegna che il karma non sbaglia direzione: se semini monete con spine di disprezzo, raccoglierai una montagna d'oro, ma ti pungerai con ogni pezzo cercando di abbracciare qualcuno.</p>

                <!-- ZH -->
                <p class="zh" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">在古老的瓦拉纳西城，住着一个名叫维马尔（Vimal）的富有青年，他以自己的慷慨大方而自豪。维马尔经常去广场，带着傲慢的神情向乞丐扔金币，享受看着他们争抢金币的样子。“看他们为了我的光芒而爬行！”他笑着对朋友们说，同时指着那些穷人的伤疤和破烂的衣服。他给出的很多，但每一枚硬币都伴随着一个残酷的笑话或一个深恶痛绝的眼神。他认为财富赋予了他优越的宝座，让他可以评判他人的不幸。</p>
                <p class="zh" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">多年过去了，正如业力所定，维马尔的慷慨为他带来了更多的财富。他成了该地区最繁荣的人，拥有的宫殿在阳光下熠熠生辉。然而，他的社交圈开始发生一些奇怪的事情。维马尔举办了传奇般的派对，在最好的音乐和美酒上花费了巨资，但他很快意识到气氛是冰冷的。他注意到，当他走进一个房间时，窃窃私语就会停止，而一旦他转身，空气中就充满了掩饰的笑声。他的“朋友”在桌旁吃着他的饭，但他们的眼神里闪烁着他以前表现出来的同样的嘲弄。</p>
                <p class="zh" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">一天，维马尔听到他最亲近的一位客人说：“真可怜，他以为金子能掩盖他试图购买我们钦佩时的滑稽样子。他只是个拿着硬币的傻瓜。”那一刻，维马尔想起了那个被他扔过硬币、还嘲笑过其孤儿身份的乞丐孩子的脸。他明白自己建造了一座金宫，但水泥却是他播下的嘲弄。他拥有金钱能买到的一切，唯独缺少灵魂最需要的东西：另一个人的真诚尊重。</p>
                <p class="zh" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">维马尔在空荡荡的大厅里度过了余生，他意识到真正的慈善不是给予你多余的东西，而是承认你在他人身上的脆弱。他的伊基盖（Ikigai）已经变暗了，因为他忘记了没有荣誉的财富是金色的荆棘冠冕。他的故事告诉我们，业力不会错位：如果你带着轻蔑的刺播下硬币，你将收获一座金山，但当你试图拥抱某人时，每一块硬币都会刺伤你。</p>

                <!-- AR -->
                <p class="ar" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">في مدينة فاراناسي القديمة، كان يعيش شاب ثري يدعى فيمال يتفاخر بكرمه الكبير. اعتاد فيمال الخروج إلى الساحات، وبإيماءة متعالية، يلقي العملات الذهبية على المتسولين، مستمتعاً برؤيتهم يتشاجرون عليها. كان يقول ضاحكاً لأصدقائه وهو يشير إلى ندوب الفقراء وأسمالهم: "انظروا كيف يزحفون من أجل بريقي!". لقد كان يعطي الكثير، لكن كل عملة كانت مصحوبة بنكتة قاسية أو نظرة ازدراء عميق. كان يعتقد أن ثروته تمنحه عرشاً من التفوق يمكنه من خلاله الحكم على بؤس الآخرين.</p>
                <p class="ar" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">مرت السنين وكما تملي الكارما، جلب كرم فيمال له ثروة أكبر. أصبح الرجل الأكثر ازدهاراً في المنطقة، وصاحب القصور التي تذهل الشمس. ومع ذلك، بدأ شيء غريب يحدث في دائرته الاجتماعية. كان فيمال ينظم حفلات أسطورية، وينفق ثروات على أفضل الموسيقيين والخمور، لكنه سرعان ما أدرك أن الجو كان بارداً كالثلج. لاحظ أنه في اللحظة التي يدخل فيها غرفة، تتوقف الهمسات، وبمجرد أن يدير ظهره، يمتلئ الهواء بالضحك الخفي. كان "أصدقاؤه" يأكلون من مائدته، لكن أعينهم كانت تلمع بنفس السخرية التي أظهرها هو في الماضي.</p>
                <p class="ar" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">ذات يوم، سمع فيمال أقرب ضيوفه يقول: "إنه أمر مثير للشفقة، يعتقد أن ذهبه يخفي كم يبدو مثيراً للسخرية وهو يحاول شراء إعجابنا. إنه مجرد أحمق لديه عملات معدنية". في تلك اللحظة، تذكر فيمال وجه الطفل المتسول الذي ألقى إليه بعملة معدنية وهو يسخر من كونه يتيماً. أدرك أنه بنى قصراً من الذهب، لكن الأسمنت كان هو السخرية التي زرعها. كان لديه كل ما يمكن للمال شراؤه، باستثناء الشيء الوحيد الذي كانت روحه بحاجة إليه: الاحترام الصادق من إنسان آخر.</p>
                <p class="ar" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">قضى فيمال بقية أيامه في صمت قاعاته الفارغة، مدركاً أن الصدقة الحقيقية ليست في إعطاء ما يفيض عنك، بل في التعرف على هشاشتك في الآخر. لقد أظلم الـ "إيكيغاي" الخاص به لأنه نسي أن الثروة بدون كرامة هي تاج من الأشواك الذهبية. تعلمنا قصته أن الكارما لا تخطئ في اتجاهها: إذا زرعت عملات معدنية بأشواك الازدراء، فسوف تحصد جبلاً من الذهب، لكنك ستجرح نفسك بكل قطعة عند محاولة احتضان شخص ما.</p>

                <!-- RU -->
                <p class="ru" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">В древнем городе Варанаси жил богатый юноша по имени Вимал, который хвастался своей великой щедростью. Вимал часто выходил на площади и с высокомерным видом бросал золотые монеты нищим, забавляясь тем, как они дерутся за них. «Смотрите, как они ползают ради моего блеска!» — говорил он со смехом своим друзьям, указывая на шрамы и лохмотья нуждающихся. Он давал много, но каждая монета сопровождалась жестокой шуткой или взглядом, полным глубокого отвращения. Он верил, что богатство дает ему трон превосходства, с которого он может судить о чужих несчастьях.</p>
                <p class="ru" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Шли годы, и, как предписывает карма, щедрость Вимала принесла ему еще больше богатств. Он стал самым процветающим человеком в регионе, владельцем дворцов, ослеплявших солнце. Однако в его социальном кругу начало происходить нечто странное. Вимал устраивал легендарные вечеринки, тратя целые состояния на лучших музыкантов и вина, но вскоре он понял, что атмосфера вокруг была ледяной. Он замечал, что в тот момент, когда он входил в комнату, шепот прекращался, а как только он отворачивался, воздух наполнялся скрытым смехом. Его «друзья» ели за его столом, но их глаза сверкали той же насмешкой, которую он когда-то проявлял сам.</p>
                <p class="ru" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Однажды Вимал услышал, как его ближайший гость сказал: «Это жалко; он думает, что его золото скрывает, как нелепо он выглядит, пытаясь купить наше восхищение. Он просто дурак с монетами». В тот миг Вимал вспомнил лицо ребенка-нищего, которому он бросил монету, смеясь над его сиротством. Он понял, что построил золотой дворец, но цементом были насмешки, которые он посеял. У него было всё, что можно купить за деньги, кроме единственного, в чем нуждалась его душа: искреннего уважения другого человека.</p>
                <p class="ru" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Вимал провел остаток дней в тишине своих пустых залов, осознав, что истинная благотворительность — это не отдавать лишнее, а признавать в другом собственную хрупкость. Его Икигай померк, потому что он забыл, что богатство без чести — это венец из золотых шипов. Его история учит нас, что карма не ошибается адресом: если сеять монеты с шипами презрения, вы соберете гору золота, но уколетесь о каждую монету, пытаясь кого-то обнять.</p>

                <!-- DE -->
                <p class="de" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">In der alten Stadt Varanasi lebte ein reicher junger Mann namens Vimal, der mit seiner großen Großzügigkeit prahlte. Vimal ging oft auf die Plätze und warf mit vornehmer Geste den Bettlern Goldmünzen zu, wobei er es genoss, zuzusehen, wie sie sich darum stritten. „Seht, wie sie für meinen Glanz kriechen!“, sagte er lachend zu seinen Freunden, während er auf die Narben und Lumpen der Bedürftigen deutete. Er gab viel, aber jede Münze war von einem grausamen Witz oder einem Blick tiefer Abscheu begleitet. Er glaubte, sein Reichtum verleihe ihm einen Thron der Überlegenheit, von dem aus er über das Unglück anderer urteilen könne.</p>
                <p class="de" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Die Jahre vergingen, und wie das Karma es vorschreibt, brachte Vimals Großzügigkeit ihm noch mehr Reichtum ein. Er wurde zum wohlhabendsten Mann der Region, Besitzer von Palästen, die in der Sonne glänzten. Doch in seinem sozialen Umfeld geschah etwas Seltsames. Vimal veranstaltete legendäre Feste und gab Vermögen für die besten Musiker und Weine aus, merkte aber bald, dass die Atmosphäre eisig war. Er bemerkte, wie das Gemurmel verstummte, sobald er einen Raum betrat, und sobald er sich umdrehte, die Luft von verstecktem Lachen erfüllt war. Seine „Freunde“ aßen an seinem Tisch, aber ihre Augen glänzten mit demselben Spott, den er einst gezeigt hatte.</p>
                <p class="de" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Eines Tages hörte Vimal seinen engsten Gast sagen: „Es ist erbärmlich; er glaubt, sein Gold könne verbergen, wie lächerlich er aussieht, wenn er versucht, unsere Bewunderung zu kaufen. Er ist nur ein Narr mit Münzen.“ In diesem Moment erinnerte sich Vimal an das Gesicht des bettelnden Kindes, dem er eine Münze zugeworfen hatte, während er über seine Verwaistheit lachte. Er begriff, dass er einen goldenen Palast gebaut hatte, dessen Zement aber der Spott war, den er gesät hatte. Er besaß alles, was man für Geld kaufen konnte, außer dem Einzigen, was seine Seele brauchte: den aufrichtigen Respekt eines anderen Menschen.</p>
                <p class="de" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Vimal verbrachte den Rest seiner Tage in der Stille seiner leeren Hallen und erkannte, dass wahre Wohltätigkeit nicht darin besteht, das zu geben, was man übrig hat, sondern die eigene Zerbrechlichkeit im anderen zu erkennen. Sein Ikigai war verdunkelt, weil er vergessen hatte, dass Reichtum ohne Ehre eine Krone aus goldenen Dornen ist. Seine Geschichte lehrt uns, dass das Karma nicht in die falsche Richtung geht: Wenn du Münzen mit Dornen der Verachtung säst, wirst du einen Berg Gold ernten, dich aber an jedem Stück stechen, wenn du versuchst, jemanden zu umarmen.</p>

                <!-- FR -->
                <p class="fr" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Dans l'ancienne ville de Bénarès, vivait un jeune homme riche nommé Vimal qui se vantait de sa grande générosité. Vimal avait l'habitude d'aller sur les places et, d'un geste hautain, jetait des pièces d'or aux mendiants, s'amusant à les voir se battre pour elles. « Regardez comment ils rampent pour mon éclat ! », disait-il en riant à ses amis, tout en montrant les cicatrices et les haillons des nécessiteux. Il donnait beaucoup, mais chaque pièce était accompagnée d'une plaisanterie cruelle ou d'un regard de profond dégoût. Il croyait que sa richesse lui conférait un trône de supériorité d'où il pouvait juger le malheur d'autrui.</p>
                <p class="fr" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Les années passèrent et, comme le dicte le karma, la générosité de Vimal lui apporta encore plus de richesses. Il devint l'homme le plus prospère de la région, propriétaire de palais qui éblouissaient le soleil. Cependant, quelque chose d'étrange commença à se produire dans son cercle social. Vimal organisait des fêtes légendaires, dépensant des fortunes pour les meilleurs musiciens et vins, mais il se rendit vite compte que l'atmosphère était glaciale. Il remarquait que, dès qu'il entrait dans une pièce, les murmures cessaient, et dès qu'il tournait le dos, l'air s'emplissait de rires étouffés. Ses « amis » mangeaient à sa table, mais leurs yeux brillaient de la même moquerie qu'il avait montrée autrefois.</p>
                <p class="fr" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Un jour, Vimal entendit son invité le plus proche dire : « C'est pathétique ; il croit que son or cache à quel point il est ridicule en essayant d'acheter notre admiration. C'est juste un idiot avec des pièces ». À cet instant, Vimal se souvint du visage de l'enfant mendiant à qui il avait jeté une pièce en riant de son orphelinat. Il comprit qu'il avait construit un palais d'or, mais que le ciment était la moquerie qu'il avait semée. Il avait tout ce que l'argent pouvait acheter, sauf la seule chose dont son âme avait besoin : le respect sincère d'un autre être humain.</p>
                <p class="fr" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Vimal passa le reste de ses jours dans le silence de ses salons vides, réalisant que la véritable charité n'est pas de donner ce que l'on a en trop, mais de reconnaître sa propre fragilité en l'autre. Son Ikigai s'était obscurci parce qu'il avait oublié que la richesse sans honneur est une couronne d'épines dorées. Son histoire nous enseigne que le karma ne se trompe pas de direction : si vous semez des pièces avec des épines de dédain, vous récolterez une montagne d'or, mais vous vous piquerez avec chaque pièce en essayant d'embrasser quelqu'un.</p>

                <!-- JA -->
                <p class="ja" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">古代都市バラナシに、自らの寛大さを自慢するヴィマルという名の若い富豪が住んでいました。ヴィマルはよく広場に出かけ、傲慢な仕草で物乞いたちに金貨を投げ、彼らがそれを奪い合うのを見て楽しんでいました。「私の輝きを求めて這いつくばる姿を見ろ！」と、彼は貧しい人々の傷跡やぼろ布を指差しながら、友人たちに笑いながら言いました。彼は多くを与えましたが、どの硬貨にも残酷な冗談や深い嫌悪の眼差しが添えられていました。彼は、自分の富が他人の不幸を裁くことのできる優越の王座を自分に与えてくれていると信じていたのです。</p>
                <p class="ja" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">歳月が流れ、カルマが命ずる通り、ヴィマルの寛大さは彼にさらなる富をもたらしました。彼はその地域で最も豊かな男となり、太陽に映える宮殿の主となりました。しかし、彼の社交界で奇妙なことが起こり始めました。ヴィマルは最高の音楽家やワインに大金を投じて伝説的なパーティーを開催しましたが、すぐにその場の空気が凍りついていることに気づきました。彼が部屋に入った瞬間に囁き声が止まり、彼が背を向けた途端、空気が忍び笑いで満たされるのに気づきました。彼の「友人」たちは彼の食卓で食事をしていましたが、その目はかつて彼が見せたのと同じ嘲笑で輝いていました。</p>
                <p class="ja" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">ある日、ヴィマルは最も親しい客がこう言うのを耳にしました。「哀れなものだ。彼は、自分の金が、私たちの賞賛を買おうとしている自分の滑稽さを隠せていると思っている。硬貨を持ったただの馬鹿だ」。その瞬間、ヴィマルは、孤児であることを笑いながら硬貨を投げつけた物乞いの子供の顔を思い出しました。彼は金の宮殿を建てましたが、そのセメントは自分がまいた嘲笑であったことを理解しました。彼は金で買えるものはすべて持っていましたが、魂が必要としていた唯一のもの、すなわち他人の心からの尊敬だけは持っていませんでした。</p>
                <p class="ja" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">ヴィマルは残りの日々を空っぽの広間の静寂の中で過ごし、真の慈善とは余ったものを与えることではなく、他者の中に自分自身の脆弱さを認めることなのだと気づきました。彼の生きがい（Ikigai）は、名誉のない富は黄金の棘の冠であることを忘れていたために、曇ってしまいました。彼の物語は、カルマが方向を間違えないことを教えてくれます。軽蔑の棘とともに硬貨をまけば、収穫した金山に抱きつこうとするたびに、一つ一つの硬貨に刺されることになるのです。</p>

                <!-- PT -->
                <p class="pt" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Na antiga cidade de Benares, vivia um jovem rico chamado Vimal que se gabava da sua grande generosidade. Vimal costumava ir às praças e, com um gesto altivo, lançava moedas de ouro aos mendigos, divertindo-se a vê-los lutar por elas. "Vejam como rastejam pelo meu brilho!", dizia entre risos aos seus amigos, enquanto apontava para as cicatrizes e os farrapos dos necessitados. Dava muito, mas cada moeda era acompanhada por uma piada cruel ou um olhar de profundo asco. Acreditava que a sua riqueza lhe conferia um trono de superioridade a partir do qual podia julgar a desgraça alheia.</p>
                <p class="pt" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Os anos passaram e, tal como dita o karma, a generosidade de Vimal trouxe-lhe ainda mais riquezas. Tornou-se o homem mais próspero da região, dono de palácios que deslumbravam o sol. No entanto, algo estranho começou a acontecer no seu círculo social. Vimal organizava festas lendárias, gastando fortunas nos melhores músicos e vinhos, mas depressa se deu conta de que o ambiente era gélido. Notava como, no momento em que entrava numa sala, os murmúrios paravam, e assim que se virava de costas, o ar enchia-se de risos dissimulados. Os seus "amigos" comiam à sua mesa, mas os seus olhos brilhavam com o mesmo deboche que ele mostrara outrora.</p>
                <p class="pt" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Um día, Vimal ouviu o seu convidado mais próximo dizer: "É patético, ele acredita que o seu ouro esconde o quão ridículo parece ao tentar comprar a nossa admiração. É apenas um tolo com moedas". Nesse instante, Vimal recordou o rosto do menino mendigo a quem tinha lançado uma moeda enquanto se ria da sua orfandade. Compreendeu que tinha construído um palácio de ouro, mas que o cimento eram os deboches que tinha semeado. Tinha tudo o que o dinheiro podia comprar, exceto a única coisa que a sua alma necessitava: o respeito sincero de outro ser humano.</p>
                <p class="pt" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Vimal passou o resto dos seus dias no silêncio dos seus salões vazios, dando-se conta de que a verdadera caridade não é dar o que te sobra, mas reconhecer a tua própria fragilidade no outro. O seu Ikigai tinha escurecido porque se esquecera de que a riqueza sem honra é uma coroa de espinhos dourados. A sua história ensina-nos que o karma não se engana na direção: se semeias moedas com espinhos de desprezo, recolherás uma montanha de ouro, mas picar-te-ás com cada peça ao tentar abraçar alguém.</p>

                <!-- VI -->
                <p class="vi" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Tại thành phố Varanasi cổ kính, có một thiếu gia giàu có tên là Vimal, người luôn khoe khoang về lòng hào phóng to lớn của mình. Vimal thường ra các quảng trường và với cử chỉ cao ngạo, ném những đồng tiền vàng cho những người ăn xin, thích thú khi thấy họ tranh giành chúng. "Nhìn xem họ bò lết vì sự hào nhoáng của ta kìa!", ông vừa cười vừa nói với bạn bè mình, trong khi chỉ vào những vết sẹo và bộ quần áo rách rưới của những người khốn khổ. Ông cho đi rất nhiều, nhưng mỗi đồng tiền đều kèm theo một lời đùa cợt tàn nhẫn hoặc một ánh nhìn khinh miệt sâu sắc. Ông tin rằng sự giàu có mang lại cho mình một ngai vàng ưu việt, từ đó có thể phán xét nỗi bất hạnh của người khác.</p>
                <p class="vi" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Năm tháng trôi qua và đúng như luật nhân quả, lòng hào phóng của Vimal đã mang lại cho ông nhiều của cải hơn nữa. Ông trở thành người thịnh vượng nhất vùng, chủ nhân của những cung điện làm lóa mắt cả ánh mặt trời. Tuy nhiên, một điều kỳ lạ bắt đầu xảy ra trong vòng tròn xã hội của ông. Vimal tổ chức những bữa tiệc huyền thoại, chi cả gia tài cho những nhạc sĩ và rượu ngon nhất, nhưng ông sớm nhận ra bầu không khí thật băng giá. Ông nhận thấy khoảnh khắc mình bước vào phòng, những tiếng xì xào dừng lại, và ngay khi ông quay lưng đi, không gian lại tràn ngập những tiếng cười vụng trộm. Những "người bạn" của ông ăn trên bàn tiệc của ông, nhưng mắt họ lại tỏa ra vẻ chế nhạo giống như ông đã từng thể hiện ngày trước.</p>
                <p class="vi" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Một ngày nọ, Vimal nghe thấy người khách thân thiết nhất của mình nói: "Thật thảm hại, hắn ta tin rằng vàng bạc có thể che giấu vẻ nực cười của mình khi cố gắng mua sự ngưỡng mộ của chúng ta. Hắn chỉ là một kẻ ngốc với những đồng tiền." Ngay lúc đó, Vimal nhớ lại khuôn mặt của đứa trẻ ăn xin mà ông đã ném đồng tiền vào khi cười nhạo sự mồ côi của nó. Ông hiểu rằng mình đã xây một cung điện bằng vàng, nhưng chất kết dính lại là những lời chế nhạo mà ông đã gieo rắc. Ông có mọi thứ tiền mua được, ngoại trừ thứ duy nhất linh hồn ông cần: sự tôn trọng chân thành của một con người khác.</p>
                <p class="vi" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Vimal dành phần đời còn lại trong sự tĩnh lặng của những sảnh đường trống vắng, nhận ra rằng lòng từ thiện thực sự không phải là cho đi những gì bạn dư thừa, mà là nhận ra sự mong manh của chính mình nơi người khác. Ikigai của ông đã mờ mịt vì ông đã quên rằng giàu sang mà không có danh dự là một vương miện bằng gai vàng. Câu chuyện của ông dạy chúng ta rằng nhân quả không đi nhầm hướng: nếu bạn gieo những đồng tiền bằng cái gai của sự coi thường, bạn sẽ gặt được núi vàng, nhưng bạn sẽ bị đâm đau bởi mỗi đồng tiền khi cố gắng ôm lấy ai đó.</p>
            </div>

            <!-- ═══ ART ═══ -->
            <div class="final-art fade-in" style="text-align: center; margin-top: 4rem; margin-bottom: 2rem;">
                <img src="assets/art.jpg" alt="Obra de Arte Karma LXII" style="max-width: 100%; border-radius: 8px; border: 1px solid var(--gold); box-shadow: 0 10px 30px rgba(0,0,0,0.5);">
            </div>

            <!-- ═══ MORAL ═══ -->
            <div class="moral fade-in">
                <span class="es">La riqueza que humilla es una cárcel de oro; da con amor y serás rico en respeto, da con burla y serás pobre en medio de tesoros.</span>
                <span class="en">Wealth that humiliates is a golden prison; give with love and you will be rich in respect, give with mockery and you will be poor in the midst of treasures.</span>
                <span class="it">La ricchezza che umilia è una prigione d'oro; dai con amore e sarai ricco di rispetto, dai con scherno e sarai povero in mezzo ai tesori.</span>
                <span class="zh">羞辱他人的财富是黄金牢房；用爱施予，你将富有尊重；用嘲弄施予，你将在宝藏中贫穷。</span>
                <span class="ar">الثروة التي تذل هي سجن ذهبي؛ أعطِ بحب وستكون غنياً بالاحترام، أعطِ بسخرية وستكون فقيراً وسط الكنوز.</span>
                <span class="ru">Богатство, которое унижает — это золотая тюрьма; давай с любовью, и будешь богат уважением, давай с насмешкой, и будешь беден среди сокровищ.</span>
                <span class="de">Reichtum, der demütigt, ist ein goldenes Gefängnis; gib mit Liebe und du wirst reich an Respekt sein, gib mit Spott und du wirst arm inmitten von Schätzen sein.</span>
                <span class="fr">La richesse qui humilie est une prison dorée ; donne avec amour et tu seras riche de respect, donne avec dérision et tu seras pauvre au milieu des trésors.</span>
                <span class="ja">屈辱を与える富は黄金の牢獄です。愛とともに与えれば尊敬において富み、嘲笑とともに与えれば宝物の中で貧しくなるでしょう。</span>
                <span class="pt">A riqueza que humilha é uma prisão de ouro; dá com amor e serás rico em respeito, dá com deboche e serás pobre no meio de tesouros.</span>
                <span class="vi">Sự giàu sang làm nhục người khác là ngục tù bằng vàng; hãy cho đi bằng tình thương và bạn sẽ giàu sự tôn trọng, cho đi bằng sự chế nhạo và bạn sẽ nghèo nàn giữa những kho báu.</span>
            </div>

            <center class="fade-in" style="margin-top: 4rem;">
                <img src="assets/hero.jpg" alt="Karma LXII Full" style="max-width: 600px; width: 100%; border-radius: 8px; border: 1px solid rgba(197,160,89,0.3); box-shadow: 0 20px 40px rgba(0,0,0,0.5);">
            </center>

            <!-- ═══ INSPIRACIÓN ORIGINAL ═══ -->
            <div class="original-inspiration fade-in" style="margin-top: 5rem; padding-top: 3rem; border-top: 1px solid rgba(197,160,89,0.3);">
                <h3 class="es" style="color: var(--gold); text-align: center; margin-bottom: 2rem; font-family: 'Cinzel', serif;">La Inspiración Original</h3>
                <h3 class="en" style="color: var(--gold); text-align: center; margin-bottom: 2rem; font-family: 'Cinzel', serif;">The Original Inspiration</h3>

                <center>
                    <img src="assets/pasaje_original.png" alt="Tranh Nhân Quả Original" style="max-width: 100%; border-radius: 8px; border: 1px solid var(--gold); box-shadow: 0 10px 30px rgba(0,0,0,0.5); margin-bottom: 2rem;">
                </center>

                <div class="translation-box" style="background: rgba(0,0,0,0.4); padding: 2rem; border-radius: 12px; border-left: 4px solid var(--gold); max-width: 800px; margin: 0 auto;">
                    <p class="vi" style="color: #fff; font-style: italic; margin-bottom: 2rem; font-family: 'EB Garamond', serif; font-size: 1.2rem;">
                        <strong>🇻🇳 Tiếng Việt:</strong><br>Nhân: Bố thí mà không tôn trọng người.<br>Quả: Giàu mà không được người thương kính.
                    </p>
                    <p style="color: #ddd; margin-bottom: 1.5rem;"><strong>🇬🇧 English:</strong><br>Cause: Doing charity without respect.<br>Effect: Brings wealthy, but unbeloved and disrespectful people.</p>
                    <p class="es" style="color: #fff; margin-bottom: 1.5rem; background: rgba(197,160,89,0.1); padding: 1rem; border-left: 3px solid var(--gold);"><strong>Traducción Recreada:</strong><br>Causa: Realizar actos de generosidad o caridad sin respeto por la dignidad de la otra persona, ya sea por soberbia, burla o superioridad.<br>Efecto: Se obtiene riqueza material, pero se vive rodeado de personas que no te aman ni te respetan, convirtiendo tu abundancia en soledad y mofa.</p>
                </div>
            </div>

            <div class="linktree-subtle fade-in" style="margin-top: 6rem; padding: 3rem 0; border-top: 1px solid rgba(197,160,89,0.2); text-align: center;">
                <p class="es" style="color: #999; font-style: italic; margin-bottom: 1.5rem;">Si quieres conocer más sobre el proyecto o colaborar, accede a nuestro <a href="../../linktree.html" style="color: var(--gold); text-decoration: none; border-bottom: 1px dotted var(--gold);">Linktree</a>.</p>
            </div>
        </div>
    </main>

    <script src="../../shared/script.js"></script>
</body>
</html>
"""

with open("/Users/fjbanezares/libro del karma/62_dar_con_burla_desprecio/web/index.html", "w") as f:
    f.write(get_html_ch62())

print("Chapter 62 HTML successfully updated with ABSOLUTELY FULL translations.")
