
import os

def fix_ch63():
    target = "/Users/fjbanezares/libro del karma/63_silencio_injusticia/web/index.html"
    
    with open(target, 'r', encoding='utf-8') as f:
        content = f.read()

    # --- TITLES AND SUBTITLES ---
    # Chapter Title
    titles = """<span class="es">El Silencio Cómplice de la Injusticia</span>
                    <span class="en">The Complacent Silence of Injustice</span>
                    <span class="it">Il Silenzio Complice dell'Ingiustizia</span>
                    <span class="zh">对不公正的默许沉默</span>
                    <span class="ar">الصمت المتواطئ مع الظلم</span>
                    <span class="ru">Молчаливое соучастие в несправедливости</span>
                    <span class="de">Das komplizenhafte Schweigen der Ungerechtigkeit</span>
                    <span class="fr">Le Silence Complice de l'Injustice</span>
                    <span class="ja">不公正に対する黙認という共犯</span>
                    <span class="pt">O Silêncio Cúmplice da Injustiça</span>
                    <span class="vi">Sự Im Lặng Đồng Lõa Trước Bất Công</span>"""
    
    content = content.replace('<span class="es">El Silencio Cómplice de la Injusticia</span>\n                    <span class="en">The Complacent Silence of Injustice</span>\n                    <span class="it">ToDo</span><span class="zh">ToDo</span><span class="ar">ToDo</span><span class="ru">ToDo</span><span class="de">ToDo</span><span class="fr">ToDo</span><span class="ja">ToDo</span><span class="pt">ToDo</span><span class="vi">ToDo</span>', titles)

    # Subtitle
    subtitles = """<span class="es">"Quien calla ante la injusticia, apaga la luz de su propia voz; el silencio no es neutral, es el refugio del opresor."</span>
                    <span class="en">"He who remains silent before injustice extinguishes the light of his own voice; silence is not neutral, it is the refuge of the oppressor."</span>
                    <span class="it">"Chi tace davanti all'ingiustizia spegne la luce della propria voce; il silenzio non è neutrale, è il rifugio dell'oppressore."</span>
                    <span class="zh">“在不公正面前保持沉默的人熄灭了自己声音的光芒；沉默并非中立，它是压迫者的避难所。”</span>
                    <span class="ar">"من يصمت أمام الظلم يطفئ نور صوته؛ الصمت ليس حياداً، بل هو ملاذ الظالم."</span>
                    <span class="ru">«Тот, кто молчит перед лицом несправедливости, гасит свет своего собственного голоса; молчание не нейтрально, оно — убежище угнетателя».</span>
                    <span class="de">"Wer angesichts von Ungerechtigkeit schweigt, löscht das Licht der eigenen Stimme aus; Schweigen ist nicht neutral, es ist die Zuflucht des Unterdrückers."</span>
                    <span class="fr">"Celui qui se tait devant l'injustice éteint la lumière de sa propre voix ; le silence n'est pas neutre, il est le refuge de l'oppresseur."</span>
                    <span class="ja">「不公正を前に沈黙する者は、自らの声の光を消す。沈黙は中立ではなく、抑圧者の隠れ家である。」</span>
                    <span class="pt">"Quem se cala perante a injustiça apaga a luz da sua própria voz; o silêncio não é neutro, é o refúgio do opressor."</span>
                    <span class="vi">"Ai im lặng trước bất công là đang tự dập tắt ánh sáng của chính tiếng nói mình; sự im lặng không hề trung lập, nó là nơi trú ẩn của kẻ áp bức."</span>"""
    
    content = content.replace('<span class="es">"Quien calla ante la injusticia, apaga la luz de su propia voz; el silencio no es neutral, es el refugio del opresor."</span>\n                    <span class="en">"He who remains silent before injustice extinguishes the light of his own voice; silence is not neutral, it is the refuge of the oppressor."</span>\n                    <span class="it">ToDo</span><span class="zh">ToDo</span><span class="ar">ToDo</span><span class="ru">ToDo</span><span class="de">ToDo</span><span class="fr">ToDo</span><span class="ja">ToDo</span><span class="pt">ToDo</span><span class="vi">ToDo</span>', subtitles)

    # Chapter Num
    chap_nums = """<span class="es">CAPÍTULO LXIII</span><span class="en">CHAPTER LXIII</span><span class="it">CAPITOLO LXIII</span><span class="zh">第六十三章</span><span class="ar">الفصل الثالث والستون</span><span class="ru">ГЛАВА LXIII</span><span class="de">KAPITEL LXIII</span><span class="fr">CHAPITRE LXIII</span><span class="ja">第63章</span><span class="pt">CAPÍTULO LXIII</span><span class="vi">CHƯƠNG LXIII</span>"""
    content = content.replace('<span class="es">CAPÍTULO LXIII</span><span class="en">CHAPTER LXIII</span><span class="it">ToDo</span><span class="zh">ToDo</span><span class="ar">ToDo</span><span class="ru">ToDo</span><span class="de">ToDo</span><span class="fr">ToDo</span><span class="ja">ToDo</span><span class="pt">ToDo</span><span class="vi">ToDo</span>', chap_nums)

    # --- EXPLANATION PARAGRAPHS ---
    
    p1_translations = """
                <p class="it"><span class="drop-cap">L</span>a voce umana è il ponte sacro tra il pensiero e la giustizia, un dono divino che ci permette di testimoniare la Verità in un mondo spesso oscurato dall'errore. Tuttavia, esiste un veleno invisibile che corrode l'anima con più forza della menzogna stessa: il silenzio complice. Tacere quando vediamo un fratello essere ingiustamente vessato non è un atto di prudenza né di saggezza, ma un tradimento del nostro scopo più profondo come esseri senzienti. L'universo ci ha concesso il linguaggio per essere scudi degli innocenti, non per nasconderci dietro la comodità dell'anonimato.</p>
                <p class="zh"><span class="drop-cap">人</span>类的声音是思想与正义之间的神圣桥梁，是一份神圣的礼物，让我们在经常被错误笼罩的世界中见证真理。然而，有一种无形的毒药比谎言本身更能强烈地侵蚀灵魂：默许的沉默。当我们看到同胞受到不公正的折磨时保持沉默，这既不是审慎也不是智慧的行为，而是对我们作为有意识生物最深层使命的背叛。宇宙赋予我们语言是为了让我们成为无辜者的盾牌，而不是躲在匿名的舒适区之后。</p>
                <p class="ar"><span class="drop-cap">ا</span>لصوت البشري هو الجسر المقدس بين الفكر والعدالة، وهو هبة إلهية تسمح لنا بالشهادة للحق في عالم غالباً ما يظلمه الخطأ. ومع ذلك، هناك سم غير مرئي ينخر الروح بقوة أكبر من الكذب نفسه: الصمت المتواطئ. إن الصمت عندما نرى أخاً يُظلم ليس عملاً من أعمال الحكمة أو التعقل، بل هو خيانة لغرضنا الأعمق ككائنات واعية. لقد منحنا الكون اللغة لنكون دروعاً للأبرياء، لا لنختبئ خلف راحة المجهول.</p>
                <p class="ru"><span class="drop-cap">Ч</span>еловеческий голос — это священный мост между мыслью и справедливостью, божественный дар, позволяющий нам свидетельствовать об Истине в мире, часто омраченном заблуждениями. Однако существует невидимый яд, который разъедает душу сильнее, чем сама ложь: молчаливое соучастие. Молчать, когда мы видим, как несправедливо притесняют ближнего, — это не акт благоразумия или мудрости, а предательство нашей высшей цели как сознательных существ. Вселенная наделила нас языком, чтобы мы были щитом для невинных, а не для того, чтобы мы прятались за удобством анонимности.</p>
                <p class="de"><span class="drop-cap">D</span>ie menschliche Stimme ist die heilige Brücke zwischen Denken und Gerechtigkeit, ein göttliches Geschenk, das es uns ermöglicht, in einer oft von Irrtümern verdunkelten Welt Zeugnis für die Wahrheit abzulegen. Es gibt jedoch ein unsichtbares Gift, das die Seele stärker zerfrisst als die Lüge selbst: das komplizenhafte Schweigen. Zu schweigen, wenn wir sehen, wie ein Bruder ungerecht schikaniert wird, ist weder ein Akt der Klugheit noch der Weisheit, sondern ein Verrat an unserer tiefsten Bestimmung als bewusste Wesen. Das Universum hat uns die Sprache verliehen, damit wir Schilde für die Unschuldigen sind, und nicht, um uns hinter der Bequemlichkeit der Anonymität zu verstecken.</p>
                <p class="fr"><span class="drop-cap">L</span>a voix humaine est le pont sacré entre la pensée et la justice, un don divin qui nous permet de témoigner de la Vérité dans un monde souvent obscurci par l'erreur. Cependant, il existe un poison invisible qui corrode l'âme avec plus de force que le mensonge lui-même : le silence complice. Se taire lorsque nous voyons un frère être injustement brimé n'est pas un acte de prudence ni de sagesse, mais une trahison de notre mission la plus profonde en tant qu'êtres conscients. L'univers nous a accordé le langage pour être les boucliers des innocents, non pour nous cacher derrière le confort de l'anonymat.</p>
                <p class="ja"><span class="drop-cap">人</span>間の声は思考と正義の間の神聖な架け橋であり、過ちに覆われがちな世界で真理を証言することを可能にする神聖な贈り物です。しかし、嘘そのものよりも強く魂を蝕む目に見えない毒が存在します。それが「黙認」という沈黙です。同胞が不当に苦しめられているのを見て沈黙することは、慎重さでも知恵でもなく、意識ある存在としての私たちの最も深い目的への裏切りです。宇宙が私たちに言語を授けたのは、無実の人々の盾となるためであり、匿名の快適さの背後に隠れるためではありません。</p>
                <p class="pt"><span class="drop-cap">A</span> voz humana é a ponte sagrada entre o pensamento e a justiça, um dom divino que nos permite dar testemunho da Verdade num mundo frequentemente obscurecido pelo erro. No entanto, existe um veneno invisível que corrói a alma com mais força do que a própria mentira: o silêncio cúmplice. Calar quando vemos um irmão ser injustamente maltratado não é um ato de prudenza nem de sabedoria, mas uma traição ao nosso propósito mais profundo como seres conscientes. O universo concedeu-nos a linguagem para sermos escudos dos inocentes, não para nos escondermos atrás do conforto do anonimato.</p>
                <p class="vi"><span class="drop-cap">T</span>iếng nói con người là chiếc cầu nối thiêng liêng giữa tư tưởng và công lý, một món quà thiên liêng cho phép chúng ta làm chứng cho Sự Thật trong một thế giới thường bị lu mờ bởi những sai lầm. Tuy nhiên, có một loại độc dược vô hình ăn mòn tâm hồn mạnh mẽ hơn cả lời nói dối: sự im lặng đồng lõa. Im lặng khi thấy một người anh em bị ngược đãi bất công không phải là hành động thận trọng hay khôn ngoan, mà là sự phản bội mục đích sâu xa nhất của chúng ta với tư cách là những sinh linh có ý thức. Vũ trụ ban cho chúng ta ngôn ngữ để làm lá chắn cho những người vô tội, chứ không phải để trốn tránh sau sự thoải mái của bóng tối vô danh.</p>"""

    p2_translations = """
                <p class="it">La legge del karma, nella sua precisione cristallina, non punisce gli errori con rabbia, ma ci restituisce l'esatta vibrazione che emettiamo nel mondo. Quando decidiamo di essere muti davanti al dolore altrui per proteggere la nostra piccola sicurezza personale, l'universo interpreta che abbiamo rinunciato alla facoltà di parlare. Il meccanismo è profondo e simbolico: se la tua voce non serve a difendere ciò che è giusto, perde la sua ragione d'essere nella sinfonia della creazione. Negando la nostra parola a chi ne aveva bisogno per sopravvivere a una menzogna, stiamo soffocando la nostra stessa capacità di comunicazione futura.</p>
                <p class="zh">业力法则以其如水晶般精确的方式，不是用愤怒来惩罚错误，而是向我们反馈我们向世界发出的精确振动。当我们为了保护自己微小的个人安全而选择在他人的痛苦面前保持沉默时，宇宙就会解读为我们已经放弃了说话的能力。这种机制深奥且具有象征意义：如果你的声音不能用来捍卫公正的事物，那么它在创作的交响乐中就失去了存在的理由。通过对那些需要我们的言语来度过谎言的人保持沉默，我们正在扼杀自己未来的沟通能力。</p>
                <p class="ar">قانون الكرمة، بدقته البلورية، لا يعاقب الأخطاء بغضب، بل يعيد لنا نفس الاهتزاز الذي نرسله إلى العالم. عندما نقرر أن نكون صامتين أمام ألم الآخرين لحماية أمننا الشخصي الصغير، يفسر الكون ذلك بأننا تنازلنا عن قدرتنا على الكلام. الآلية عميقة ورمزية: إذا كان صوتك لا يخدم الدفاع عما هو عادل، فإنه يفقد سبب وجوده في سيمفونية الخلق. بحرماننا كلمتنا لمن يحتاجها للنجاة من كذبة، فإننا نخنق قدرتنا المستقبلية على التواصل.</p>
                <p class="ru">Закон кармы в своей кристальной точности не наказывает за ошибки гневом, а возвращает нам именно ту вибрацию, которую мы излучаем в мир. Когда мы решаем безмолвствовать перед лицом чужой боли, чтобы защитить свою маленькую личную безопасность, Вселенная интерпретирует это так, будто мы отказались от способности говорить. Этот механизм глубок и символичен: если твой голос не служит защите справедливости, он теряет смысл своего существования в симфонии творения. Отказывая в слове тому, кто нуждался в нем, чтобы выжить среди лжи, мы удушаем нашу собственную способность к общению в будущем.</p>
                <p class="de">Das Gesetz des Karma bestraft Fehler in seiner kristallinen Präzision nicht mit Zorn, sondern gibt uns genau die Schwingung zurück, die wir in die Welt aussenden. Wenn wir uns entscheiden, angesichts des Schmerzes anderer stumm zu bleiben, um unsere eigene kleine persönliche Sicherheit zu schützen, interpretiert das Universum dies so, als hätten wir auf die Fähigkeit zu sprechen verzichtet. Der Mechanismus ist tiefgreifend und symbolisch: Wenn deine Stimme nicht dazu dient, das Gerechte zu verteidigen, verliert sie ihren Daseinsgrund in der Symphonie der Schöpfung. Indem wir unser Wort denen verweigern, die es brauchten, um eine Lüge zu überleben, ersticken wir unsere eigene zukünftige Kommunikationsfähigkeit.</p>
                <p class="fr">La loi du karma, dans sa précision cristalline, ne punit pas les erreurs avec colère, mais nous renvoie la vibration exacte que nous émettons au monde. Lorsque nous décidons d'être muets devant la douleur d'autrui pour protéger notre petite sécurité personnelle, l'univers interprète que nous avons renoncé à la faculté de parler. Le mécanisme est profond et symbolique : si votre voix ne sert pas à défendre ce qui est juste, elle perd sa raison d'être dans la symphonie de la création. En refusant notre parole à celui qui en avait besoin pour survivre à un mensonge, nous étouffons notre propre capacité de communication future.</p>
                <p class="ja">カルマの法則は、その水晶のような精密さにおいて、怒りを持って過ちを罰するのではなく、私たちが世界に発した正確な振動を私たちに返します。自分の小さな個人的な安全を守るために他人の苦痛を前に沈黙することを選んだとき、宇宙は私たちが話す能力を放棄したと解釈します。このメカニズムは深遠で象徴的です。あなたの声が正義を守るために役立たないのであれば、創造の交響曲の中で存在する理由を失います。嘘を生き延びるために言葉を必要としていた人に対して言葉を拒むことで、私たちは自分自身の将来の対話能力を窒息させているのです。</p>
                <p class="pt">A lei do carma, na sua precisão cristalina, não pune os erros com raiva, mas devolve-nos a vibração exata que emitimos ao mundo. Quando decidimos ser mudos perante a dor alheia para proteger a nossa pequena segurança pessoal, o universo interpreta que renunciámos à faculdade de falar. O mecanismo é profundo e simbólico: se a tua voz não serve para defender o que é justo, perde a sua razão de ser na sinfonia da criação. Ao negarmos a nossa palavra a quem precisava dela para sobreviver a uma mentira, estamos a asfixiar a nossa própria capacidade de comunicação futura.</p>
                <p class="vi">Luật nghiệp báo, với sự chính xác tuyệt đối, không trừng phạt sai lầm bằng cơn giận dữ, mà trả lại cho chúng ta đúng rung động mà chúng ta đã phát ra thế giới. Khi chúng ta chọn im lặng trước nỗi đau của người khác để bảo vệ sự an toàn cá nhân nhỏ bé của mình, vũ trụ hiểu rằng chúng ta đã từ bỏ khả năng nói. Cơ chế này rất sâu sắc và mang tính biểu tượng: nếu tiếng nói của bạn không phục vụ cho việc bảo vệ công lý, nó sẽ mất đi lý do tồn tại trong bản giao hưởng của tạo hóa. Khi từ chối lời nói với những người cần nó để vượt qua một lời nói dối, chúng ta đang bóp nghẹt khả năng giao tiếp của chính mình trong tương lai.</p>"""

    p3_translations = """
                <p class="it">L'"antes" di questo karma è una vita di apparente calma, in cui l'individuo evita i conflitti a scapito della propria integrità, credendo che il silenzio lo mantenga al sicuro. Il "después" è la solitudine dell'anima muta: una disconnessione totale in cui, anche se la gola emette suoni, nessuno ascolta l'essenza, o fisicamente la parola si ritira. Per allineare la nostra vita allo scopo luminoso, dobbiamo capire che la neutralità davanti all'ingiustizia non esiste; o siamo la voce della verità o siamo l'eco della tirannia. Solo usando la nostra parola con coraggio assicuriamo che l'universo mantenga aperto il canale della nostra sacra espressione.</p>
                <p class="zh">这种业力的“前因”是一种表面平静的生活，个人以牺牲正直为代价回避冲突，认为沉默能让自己安全。而“后果”是沉默灵魂的孤独：一种完全的断开，即使喉咙发出声音，也没有人听到本质，或者在身体上语言功能退缩。为了使我们的生活与光明的使命保持一致，我们必须明白，在不公正面前不存在中立；我们要么是真理的声音，要么是暴政的回声。只有勇敢地使用我们的言语，我们才能确保宇宙保持我们神圣表达的通道畅通。</p>
                <p class="ar">إن "ما قبل" هذه الكرمة هو حياة من الهدوء الظاهري، حيث يتجنب الفرد الصراعات على حساب نزاهته، معتقداً أن صمته يبقيه آمناً. أما "ما بعد" فهو وحدة الروح الخرساء: انفصال تام حيث، حتى لو أصدرت الحنجرة أصواتاً، لا أحد يسمع الجوهر، أو ينسحب الكلام جسدياً. لكي نوائم حياتنا مع الغرض المضيء، يجب أن نفهم أن الحياد أمام الظلم لا وجود له؛ فإما أن نكون صوت الحقيقة أو نكون صدى الاستبداد. فقط باستخدام كلمتنا بشجاعة، نضمن أن يبقي الكون قناة تعبيرنا المقدس مفتوحة.</p>
                <p class="ru">«До» этой кармы — это жизнь в кажущемся спокойствии, где человек избегает конфликтов ценой своей честности, веря, что молчание обеспечивает ему безопасность. «После» — это одиночество немой души: полное разобщение, когда, даже если горло издает звуки, никто не слышит сути, или же речь физически пропадает. Чтобы привести нашу жизнь в соответствие с сияющей целью, мы должны понять, что нейтралитета перед лицом несправедливости не существует; мы либо голос истины, либо эхо тирании. Только используя наше слово мужественно, мы гарантируем, что Вселенная сохранит канал нашего собственного священного самовыражения открытым.</p>
                <p class="de">Das „Vorher“ dieses Karma ist ein Leben in scheinbarer Ruhe, in dem das Individuum Konflikte auf Kosten seiner Integrität vermeidet und glaubt, dass sein Schweigen es in Sicherheit wiegt. Das „Nachher“ ist die Einsamkeit der stummen Seele: eine totale Trennung, bei der niemand das Wesen hört, selbst wenn die Kehle Töne von sich gibt, oder die Sprache sich physisch zurückzieht. Um unser Leben auf die lichte Bestimmung auszurichten, müssen wir verstehen, dass es Neutralität gegenüber Ungerechtigkeit nicht gibt; entweder sind wir die Stimme der Wahrheit oder wir sind das Echo der Tyrannei. Nur wenn wir unser Wort mutig einsetzen, stellen wir sicher, dass das Universum den Kanal unseres eigenen heiligen Ausdrucks offen hält.</p>
                <p class="fr">L'"avant" de ce karma est une vie de calme apparent, où l'individu évite les conflits au détriment de son intégrité, croyant que son silence le maintient en sécurité. L'"après" est la solitude de l'âme muette : une déconnexion totale où, même si la gorge émet des sons, personne n'en écoute l'essence, ou physiquement la parole se retire. Pour aligner notre vie sur la mission lumineuse, nous devons comprendre que la neutralité devant l'injustice n'existe pas ; soit nous sommes la voix de la vérité, soit nous sommes l'écho de la tyrannie. Ce n'est qu'en utilisant notre parole avec courage que nous assurons que l'univers maintient ouvert le canal de notre propre expression sacrée.</p> Japan訳-->
                <p class="ja">このカルマの「前」は、沈黙が自分を安全に保つと信じ、誠実さを犠牲にして葛藤を避ける表面的な平穏な生活です。その「後」は、沈黙した魂の孤独です。たとえ喉から音が出たとしても、誰もその本質を聞き取ることができない、あるいは物理的に言葉が失われるという完全な断絶です。私たちの人生を光り輝く目的と一致させるためには、不公正に対する中立は存在しないことを理解しなければなりません。私たちは真実の声であるか、あるいは暴政の残響であるかのどちらかです。勇気を持って言葉を使うことによってのみ、宇宙が私たちの神聖な表現の回路を開き続けることを保証できるのです。</p>
                <p class="pt">O "antes" deste carma é uma vida de aparente calma, onde o indivíduo evita conflitos à custa da sua integridade, acreditando que o seu silêncio o mantém seguro. O "depois" é a solidão da alma muda: uma desconexão total onde, embora a garganta emita sons, ninguém ouve a essenza, ou fisicamente a fala retira-se. Para alinhar a nossa vida com o propósito luminoso, devemos compreender que a neutralidade perante a injustiça não existe; ou somos a voz da verdade ou somos o eco da tirania. Só ao usar a nossa palavra com coragem asseguramos que o universo mantém aberto o canal da nossa própria expressão sagrada.</p>
                <p class="vi">Cái "trước" của nghiệp này là một cuộc sống có vẻ yên bình, nơi cá nhân trốn tránh xung đột bằng cái giá của sự liêm chính, tin rằng sự im lặng sẽ giữ cho mình an toàn. Cái "sau" là sự cô đơn của một tâm hồn câm lặng: một sự ngắt kết nối hoàn toàn mà ở đó, ngay cả khi cổ họng phát ra âm thanh, không ai nghe thấy thực chất, hoặc khả năng nói bị rút lại về mặt thể lý. Để điều chỉnh cuộc sống của mình theo mục đích tươi sáng, chúng ta phải hiểu rằng không có sự trung lập trước bất công; hoặc chúng ta là tiếng nói của sự thật hoặc chúng ta là tiếng vang của sự bạo tàn. Chỉ bằng cách sử dụng lời nói một cách can đảm, chúng ta mới đảm bảo rằng vũ trụ luôn mở rộng kênh biểu đạt thiêng liêng của chính mình.</p>"""

    content = content.replace('<p class="it">ToDo</p><p class="zh">ToDo</p><p class="ar">ToDo</p><p class="ru">ToDo</p><p class="de">ToDo</p><p class="fr">ToDo</p><p class="ja">ToDo</p><p class="pt">ToDo</p><p class="vi">ToDo</p>', p1_translations + p2_translations + p3_translations)

    # --- PARABLE TITLES ---
    parable_titles = """<h3 class="it" style="color: var(--gold); text-align: center; font-family: 'Cinzel', serif; margin-bottom: 2rem;">Lo Scriba dalla Gola Secca</h3>
                <h3 class="zh" style="color: var(--gold); text-align: center; font-family: 'Cinzel', serif; margin-bottom: 2rem;">咽喉干枯的抄写员</h3>
                <h3 class="ar" style="color: var(--gold); text-align: center; font-family: 'Cinzel', serif; margin-bottom: 2rem;">كاتب الحنجرة الجافة</h3>
                <h3 class="ru" style="color: var(--gold); text-align: center; font-family: 'Cinzel', serif; margin-bottom: 2rem;">Писчий с пересохшим горлом</h3>
                <h3 class="de" style="color: var(--gold); text-align: center; font-family: 'Cinzel', serif; margin-bottom: 2rem;">Der Schreiber mit der trockenen Kehle</h3>
                <h3 class="fr" style="color: var(--gold); text-align: center; font-family: 'Cinzel', serif; margin-bottom: 2rem;">Le Scribe à la Gorge Sèche</h3>
                <h3 class="ja" style="color: var(--gold); text-align: center; font-family: 'Cinzel', serif; margin-bottom: 2rem;">喉の渇いた書記官</h3>
                <h3 class="pt" style="color: var(--gold); text-align: center; font-family: 'Cinzel', serif; margin-bottom: 2rem;">O Escrivão da Garganta Seca</h3>
                <h3 class="vi" style="color: var(--gold); text-align: center; font-family: 'Cinzel', serif; margin-bottom: 2rem;">Người Chép Thuê Với Cổ Họng Khô Cằn</h3>"""
    
    content = content.replace('<h3 class="it" style="color: var(--gold); text-align: center; font-family: \'Cinzel\', serif; margin-bottom: 2rem;">ToDo</h3>\n                <h3 class="zh" style="color: var(--gold); text-align: center; font-family: \'Cinzel\', serif; margin-bottom: 2rem;">ToDo</h3>\n                <h3 class="ar" style="color: var(--gold); text-align: center; font-family: \'Cinzel\', serif; margin-bottom: 2rem;">ToDo</h3>\n                <h3 class="ru" style="color: var(--gold); text-align: center; font-family: \'Cinzel\', serif; margin-bottom: 2rem;">ToDo</h3>\n                <h3 class="de" style="color: var(--gold); text-align: center; font-family: \'Cinzel\', serif; margin-bottom: 2rem;">ToDo</h3>\n                <h3 class="fr" style="color: var(--gold); text-align: center; font-family: \'Cinzel\', serif; margin-bottom: 2rem;">ToDo</h3>\n                <h3 class="ja" style="color: var(--gold); text-align: center; font-family: \'Cinzel\', serif; margin-bottom: 2rem;">ToDo</h3>\n                <h3 class="pt" style="color: var(--gold); text-align: center; font-family: \'Cinzel\', serif; margin-bottom: 2rem;">ToDo</h3>\n                <h3 class="vi" style="color: var(--gold); text-align: center; font-family: \'Cinzel\', serif; margin-bottom: 2rem;">ToDo</h3>', parable_titles)

    # --- PARABLE PARAGRAPHS ---
    
    par_p1 = """
                <p class="it" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">C'era una volta uno scriba di nome Nahum che possedeva una voce di velluto e parole di seta. Nahum era rispettato in tutta la città per la sua eloquenza, e la sua voce era richiesta per cantare inni nel tempio e leggere leggi nel mercato. Nahum viveva orgoglioso del suo dono, ma lo custodiva gelosamente per il proprio beneficio. Un giorno, un umile anziano del villaggio fu ingiustamente accusato di aver rubato il grano sacro. Nahum, nascosto dietro una colonna, aveva visto il vero colpevole: il figlio del potente governatore locale. Tuttavia, vedendo il luccichio delle spade delle guardie e temendo per la propria posizione, Nahum chinò il capo e lasciò che il silenzio inondasse la sua gola mentre l'anziano veniva condannato all'esilio eterno nel deserto ardente.</p>
                <p class="zh" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">从前有一个名叫那鸿（Nahum）的抄写员，他拥有一副天鹅绒般的声音和丝绸般的言语。那鸿因其雄辩而受到全城的尊敬，人们邀请他去神庙唱赞美诗，在集市上宣读法律。那鸿为自己的天赋感到自豪，但他为了自己的利益而小心翼翼地守护着它。一天，村里一位谦卑的老人被诬陷偷走了神圣的谷物。躲在柱子后面的那鸿看到了真正的罪魁祸首：当地权势显赫的总督的儿子。然而，看到卫兵闪烁的剑光并担心自己的地位，那鸿低下了头，任由沉默淹没他的喉咙，而老人则被判处在烈日炎炎的沙漠中永世流放。</p>
                <p class="ar" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">كان هناك ذات مرة كاتب يدعى ناحوم، يمتلك صوتاً كالمخمل وكلمات كالحرير. كان ناحوم محترماً في جميع أنحاء المدينة لفصاحته، وكان صوته مطلوباً لغناء الترانيم في المعبد وقراءة القوانين في السوق. عاش ناحوم فخوراً بموهبته، لكنه كان يحرسها بغيرة لمصلحته الخاصة. وفي أحد الأيام، اتُهم رجل مسن متواضع من القرية ظلماً بسرقة الحبوب المقدسة. وكان ناحوم، المختبئ خلف عمود، قد رأى الجاني الحقيقي: ابن حاكم المدينة القوي. ومع ذلك، عندما رأى بريق سيوف الحراس وخاف على منصبه، أحنى ناحوم رأسه وترك الصمت يغمر حنجرته بينما حُكم على العجوز بالنفي الأبدي في الصحراء الحارقة.</p>
                <p class="ru" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Жил-был писчий по имени Наум, обладавший бархатным голосом и шелковыми словами. Наума уважали во всем городе за красноречие, его приглашали петь гимны в храме и читать законы на рыночной площади. Наум гордился своим даром, но ревностно оберегал его ради собственной выгоды. Однажды скромного деревенского старика несправедливо обвинили в краже священного зерна. Наум, спрятавшись за колонной, видел истинного виновника: сына могущественного местного губернатора. Однако, завидев блеск мечей стражи и испугавшись за свое положение, Наум склонил голову и позволил тишине затопить свое горло, пока старика приговаривали к вечному изгнанию в палящую пустыню.</p>
                <p class="de" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Es gab einmal einen Schreiber namens Nahum, der eine Stimme wie Samt und Worte wie Seide besaß. Nahum wurde in der ganzen Stadt wegen seiner Beredsamkeit geschätzt, und seine Stimme war gefragt, um Hymnen im Tempel zu singen und Gesetze auf dem Markt zu verlesen. Nahum war stolz auf seine Gabe, hütete sie jedoch eifersüchtig zu seinem eigenen Vorteil. Eines Tages wurde ein bescheidener alter Mann aus dem Dorf fälschlicherweise beschuldigt, das heilige Getreide gestohlen zu haben. Nahum, der hinter einer Säule verborgen war, hatte den wahren Schuldigen gesehen: den Sohn des mächtigen lokalen Gouverneurs. Doch als er das Blinken der Schwerter der Wachen sah und um seine eigene Stellung fürchtete, senkte Nahum den Kopf und ließ das Schweigen seine Kehle überfluten, während der alte Mann zur ewigen Verbannung in der brennenden Wüste verurteilt wurde.</p>
                <p class="fr" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Il y avait autrefois un scribe nommé Nahum qui possédait une voix de velours et des mots de soie. Nahum était respecté dans toute la ville pour son éloquence, et sa voix était sollicitée pour chanter des hymnes au temple et lire les lois au marché. Nahum vivait fier de son don, mais il le gardait jalousement pour son propre bénéfice. Un jour, un humble vieillard du village fut injustement accusé d'avoir volé le grain sacré. Nahum, caché derrière une colonne, avait vu le véritable coupable : le fils du puissant gouverneur local. Cependant, voyant l'éclat des épées des gardes et craignant pour sa propre position, Nahum baissa la tête et laissa le silence inonder sa gorge tandis que le vieillard était condamné à l'exil éternel dans le désert brûlant.</p>
                <p class="ja" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">かつてナフムという名の書記官がいました。彼はベルベットのような声とシルクのような言葉を持っていました。ナフムはその雄弁さで街中で尊敬されており、神殿で賛美歌を歌ったり、市場で法律を読み上げたりするためにその声が求められていました。ナフムは自分の才能を誇りにしていましたが、それを自分の利益のために嫉妬深く守っていました。ある日、村の控えめな老人が神聖な穀物を盗んだとして不当に告発されました。柱の陰に隠れていたナフムは、真犯人を目撃していました。それは強力な地方総督の息子でした。しかし、衛兵の剣の輝きを見て自分の地位を恐れたナフムは、頭を下げ、老人が灼熱の砂漠へと永遠の追放を宣告される間、沈黙が自分の喉を支配するのを許しました。</p>
                <p class="pt" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Houve uma vez um escrivão chamado Naum que possuía uma voz de veludo e palavras de seda. Naum era respeitado em toda a cidade pela sua eloquência, e a sua voz era solicitada para cantar hinos no templo e ler leis no mercado. Naum vivia orgulhoso do seu dom, mas guardava-o zelosamente para seu próprio benefício. Um dia, um humilde ancião da aldeia foi injustamente acusado di ter roubado o grão sagrado. Naum, escondido atrás de uma coluna, tinha visto o verdadeiro culpado: o filho do poderoso governador local. No entanto, ao ver o brilho das espadas dos guardas e temendo pela sua própria posição, Naum baixou a cabeça e deixou que o silêncio inundasse a sua garganta enquanto o ancião era condenado ao desterro eterno no deserto ardente.</p>
                <p class="vi" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Ngày xưa có một người chép thuê tên là Nahum, người sở hữu giọng nói mượt mà như nhung và những lời lẽ êm ái như lụa. Nahum được cả thành phố kính trọng vì tài hùng biện, và giọng nói của ông thường được mời để hát thánh ca trong đền thờ và đọc luật pháp ở chợ. Nahum rất tự hào về tài năng của mình, nhưng ông lại giữ nó một cách ích kỷ vì lợi ích cá nhân. Một ngày nọ, một cụ già khiêm tốn trong làng bị cáo buộc oan uổng là đã lấy trộm ngũ cốc thiêng liêng. Nahum, nấp sau một cây cột, đã nhìn thấy kẻ thủ ác thực sự: chính là con trai của vị thống đốc địa phương đầy quyền lực. Tuy nhiên, khi nhìn thấy ánh kiếm sáng loáng của lính canh và lo sợ cho địa vị của mình, Nahum đã cúi đầu và để sự im lặng lấp đầy cổ họng trong khi ông cụ bị kết án lưu đày vĩnh viễn ở sa mạc nóng bỏng.</p>"""

    par_p2 = """
                <p class="it" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Gli anni passarono e Nahum prosperò, ma il peso di quel silenzio cominciò a indurirsi nel suo petto come una pietra. Un giorno, alla nascita del suo primo figlio, Nahum volle intonare una canzone di benvenuto, una melodia che sgorgava dalla sua anima con una tenerezza infinita. Ma quando aprì la bocca, non uscì alcun suono. La sua gola era secca come la sabbia del deserto e le sue corde vocali, prima vibranti, sembravano fili di paglia bruciata. Nahum gridò nella sua mente, ma il suo corpo era una prigione di silenzio assoluto. Consultò i migliori guaritori, ma nessuno trovò una causa fisica per la sua mutismo; le sue labbra si muovevano, ma l'aria passava senza anima, senza musica, senza vita.</p>
                <p class="zh" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">几年过去了，那鸿事业有成，但那沉默的重量开始在他胸中像石头一样硬化。一天，当他的第一个孩子出生时，那鸿想唱一首欢迎曲，那是一首以无限温柔从他灵魂深处涌出的旋律。但当他张开嘴时，却发不出任何声音。他的喉咙像沙漠的沙子一样干枯，他以前充满活力的声带看起来像烧焦的草绳。那鸿在心中呐喊，但他的身体却是一个绝对沉默的监狱。他咨询了最好的治疗师，但没有人发现他失声的生理原因；他的嘴唇在动，但呼出的空气没有灵魂，没有音乐，没有生命。</p>
                <p class="ar" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">مرت السنين وازدهر ناحوم، لكن ثقل ذلك الصمت بدأ يتحجر في صدره كالحجر. وفي أحد الأيام، عند ولادة طفله الأول، أراد ناحوم أن يغني أغنية ترحيب، وهي لحن ينبع من روحه بحنان لا ينتهي. لكن عندما فتح فمه، لم يخرج أي صوت. كانت حنجرته جافة كرمال الصحراء، وحباله الصوتية، التي كانت نابضة بالحياة ذات يوم، بدت كخيوط من القش المحروق. صرخ ناحوم في عقله، لكن جسده كان سجناً من الصمت المطلق. استشار أفضل المعالجين، لكن لم يجد أحد سبباً جسدياً لخرسه؛ تحركت شفتاه، لكن الهواء مرّ بلا روح، بلا موسيقى، بلا حياة.</p>
                <p class="ru" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Прошли годы, Наум процветал, но тяжесть того молчания начала твердеть в его груди, словно камень. Однажды, когда родился его первенец, Наум захотел спеть приветственную песню — мелодию, которая исходила из его души с бесконечной нежностью. Но когда он открыл рот, не вырвалось ни звука. Его горло пересохло, как песок в пустыне, а голосовые связки, прежде вибрирующие, казались прядями обгоревшей соломы. Наум кричал в своем уме, но его тело было тюрьмой абсолютной тишины. Он обращался к лучшим лекарям, но никто не нашел физической причины его немоты; губы шевелились, но воздух проходил без души, без музыки, без жизни.</p>
                <p class="de" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Die Jahre vergingen und Nahum gedieh, doch das Gewicht jenes Schweigens begann in seiner Brust hart wie Stein zu werden. Eines Tages, als sein erstes Kind geboren wurde, wollte Nahum ein Begrüßungslied anstimmen, eine Melodie, die mit unendlicher Zärtlichkeit aus seiner Seele quoll. Doch als er den Mund öffnete, kam kein Ton heraus. Seine Kehle war trocken wie der Wüstensand, und seine früher vibrierenden Stimmbänder schienen wie verbrannte Strohhalme zu sein. Nahum schrie in seinem Geist, doch sein Körper war ein Gefängnis absoluter Stille. Er konsultierte die besten Heiler, doch keiner fand eine körperliche Ursache für seine Stummheit; seine Lippen bewegten sich, doch die Luft strömte ohne Seele, ohne Musik, ohne Leben hindurch.</p>
                <p class="fr" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Les années passèrent et Nahum prospéra, mais le poids de ce silence commença à s'endurcir dans sa poitrine comme une pierre. Un jour, à la naissance de son premier enfant, Nahum voulut entonner une chanson de bienvenue, une mélodie qui jaillissait de son âme avec une tendresse infinie. Mais quand il ouvrit la bouche, aucun son ne sortit. Sa gorge était sèche comme le sable du désert, et ses cordes vocales, autrefois vibrantes, ressemblaient à des brins de paille brûlée. Nahum cria dans son esprit, mais son corps était une prison de silence absolu. Il consulta les meilleurs guérisseurs, mais aucun ne trouva de cause physique à son mutisme ; ses lèvres bougeaient, ma l'air passait sans âme, sans musique, sans vie.</p>
                <p class="ja" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">年月が経ち、ナフムは繁栄しましたが、あの沈黙の重みは石のように彼の胸の中で固まり始めました。ある日、最初の子が生まれたとき、ナフムは歓迎の歌を歌おうとしました。それは無限の優しさとともに彼の魂から湧き上がるメロディーでした。しかし、彼が口を開けたとき、何の音も出ませんでした。彼の喉は砂漠の砂のように乾き、かつては響いていた声帯は焦げたわらの糸のようでした。ナフムは心の中で叫びましたが、彼の体は絶対的な沈黙の牢獄でした。彼は最高の治療師たちに相談しましたが、誰も彼の無言症の身体的な原因を見つけることはできませんでした。彼の唇は動きましたが、空気は魂もなく、音楽もなく、生命もなく通り過ぎるだけでした。</p>
                <p class="pt" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Os anos passaram e Naum prosperou, mas o peso daquele silêncio começou a endurecer no seu peito como uma pedra. Um dia, ao nascer o seu primeiro filho, Naum quis entoar uma canção de boas-vindas, uma melodia que brotava da sua alma com uma ternura infinita. Mas ao abrir a boca, não saiu som algum. A sua garganta estava seca como a areia do deserto, e as suas cordas vocais, antes vibrantes, pareciam fios de palha queimada. Naum gritou na sua mente, mas o seu corpo era uma prisão de silêncio absoluto. Consultou os melhores curandeiros, mas nenhum encontrou causa física para a sua mudez; os seus lábios moviam-se, mas o ar passava sem alma, sem música, sem vida.</p>
                <p class="vi" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Nhiều năm trôi qua và Nahum trở nên giàu có, nhưng sức nặng của sự im lặng đó bắt đầu xơ cứng trong lồng ngực ông như một hòn đá. Một ngày nọ, khi đứa con đầu lòng chào đời, Nahum muốn hát một bài ca chào mừng, một giai điệu trào dâng từ tâm hồn ông với sự dịu dàng vô hạn. Nhưng khi ông mở miệng, không có âm thanh nào phát ra. Cổ họng ông khô khốc như cát sa mạc, và dây thanh quản vốn rung động trước đây giờ như những sợi rơm cháy. Nahum hét lên trong tâm trí, nhưng cơ thể ông là một nhà tù của sự im lặng tuyệt đối. Ông đã tìm đến những thầy thuốc giỏi nhất, nhưng không ai tìm ra nguyên nhân vật lý cho sự câm lặng của ông; đôi môi ông vẫn mấp máy, nhưng không khí đi qua mà không có linh hồn, không có âm nhạc, không có sự sống.</p>"""

    par_p3 = """
                <p class="it" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Disperato, Nahum camminò fino alla cima del Monte dell'Eco, dove viveva un eremita che parlava con il vento. Senza poter articolare parola, lo scriba scrisse il suo dolore sulla terra. L'anziano, guardandolo con compassione, gli disse: "Nahum, la tua voce non è mai stata tua; era un prestito del cielo per essere la spada della verità. Negandola a quell'anziano innocente, hai rotto il patto con la creazione. La Verità si è ritirata da te perché tu ti sei ritirato da lei quando aveva più bisogno di te". Nahum cadde in ginocchio e, per la prima volta, le sue lacrime parlarono per lui. Capì che il suo mutismo non era una punizione, ma il riflesso esatto del vuoto che aveva lasciato nel mondo con la sua codardia.</p>
                <p class="zh" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">绝望中，那鸿走向回声山的顶峰，那里住着一位能与风对话的隐士。因为无法说话，抄写员在土地上写下了他的痛苦。老人怜悯地看着他，说道：“那鸿，你的声音从来不属于你；它是上天借给你的，用来做真理之剑。当你拒绝为那位无辜的老人发声时，你打破了与创作的契约。真理已经从你身边撤退，因为当它最需要你的时候，你退缩了。”那鸿跪倒在地，第一次，他的眼泪替他说话。他明白他的失声不是一种惩罚，而由于他的懦弱而在世界上留下的空白的精确反映。</p>
                <p class="ar" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">يائساً، سار ناحوم إلى قمة جبل الصدى، حيث كان يعيش ناسك يتحدث مع الريح. وبدون القدرة على نطق كلمة واحدة، كتب الكاتب حزنه في الأرض. قال له العجوز، وهو ينظر إليه بشفقة: "يا ناحوم، صوتك لم يكن ملكك أبداً؛ لقد كان قرضاً من السماء لتكون سيف الحق. وبمنعه عن ذلك الشيخ البريء، نقضت العهد مع الخلق. لقد انسحب الحق منك لأنك انسحبت منه عندما كان في أمس الحاجة إليك". سقط ناحوم على ركبتيه، ولأول مرة، تكلمت دموعه عنه. فهم أن خرسه لم يكن عقاباً، بل كان الانعكاس الدقيق للفراغ الذي تركه في العالم بجبنه.</p>
                <p class="ru" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">В отчаянии Наум поднялся на вершину Горы Эха, где жил отшельник, говоривший с ветром. Не в силах произнести ни слова, писчий написал о своем горе на земле. Старик, взглянув на него с состраданием, сказал: «Наум, твой голос никогда не принадлежал тебе; это был заем у небес, чтобы быть мечом истины. Отказав в нем тому невинному старику, ты нарушил завет с творением. Истина отступила от тебя, потому что ты отступил от нее, когда был ей больше всего нужен». Наум упал на колени, и впервые слезы заговорили за него. Он понял, что его немота — не наказание, а точное отражение той пустоты, которую он оставил в мире своей трусостью.</p>
                <p class="de" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Verzweifelt wanderte Nahum zum Gipfel des Echoberges, wo ein Eremit lebte, der mit dem Wind sprach. Unfähig, ein Wort zu artikulieren, schrieb der Schreiber seinen Kummer in den Boden. Der alte Mann sah ihn mit Mitgefühl an und sagte: „Nahum, deine Stimme war nie dein; sie war ein Leihgabe des Himmels, um das Schwert der Wahrheit zu sein. Indem du sie jenem unschuldigen alten Mann verweigert hast, hast du den Pakt mit der Schöpfung gebrochen. Die Wahrheit hat sich von dir zurückgezogen, weil du dich von ihr zurückgezogen hast, als sie dich am meisten brauchte.“ Nahum fiel auf die Knie, und zum ersten Mal sprachen seine Tränen für ihn. Er verstand, dass seine Stummheit keine Strafe war, sondern das exakte Spiegelbild der Leere, die er mit seiner Feigheit in der Welt hinterlassen hatte.</p>
                <p class="fr" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Désespéré, Nahum marcha jusqu'au sommet de la Montagne de l'Écho, où vivait un ermite qui parlait avec le vent. Incapable d'articuler un mot, le scribe écrivit sa peine sur le sol. Le vieillard, le regardant avec compassion, lui dit : « Nahum, ta voix n'a jamais été à toi ; c'était un prêt du ciel pour être l'épée de la vérité. En la refusant à ce vieillard innocent, tu as rompu le pacte avec la création. La Vérité s'est retirée de toi parce que tu t'es retiré d'elle quand elle avait le plus besoin de toi. » Nahum tomba à genoux et, pour la première fois, ses larmes parlèrent pour lui. Il comprit que son mutisme n'était pas une punition, mais le reflet exact du vide qu'il avait laissé dans le monde par sa lâcheté.</p>
                <p class="ja" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">絶望したナフムは、風と対話する隠者が住む木霊の山の頂上まで歩いていきました。言葉を発することができず、書記官は自分の悲しみを地面に書き記しました。老人は慈悲の心で彼を見つめ、こう言いました。「ナフムよ、お前の声はお前のものではなかった。それは真実の剣となるために天から貸し出されたものだ。あの無実の老人に声を貸すことを拒んだことで、お前は創造との契約を破ったのだ。真実がお前を必要としていた時にお前が真実から退いたから、真実もお前から退いたのだ」。ナフムは膝から崩れ落ち、初めて涙が彼に代わって語りました。彼の沈黙は罰ではなく、彼の臆病さによって世界に残した空白の正確な反映であることを理解しました。</p>
                <p class="pt" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Desesperado, Naum caminhou até ao cume da Montanha do Eco, onde vivia um eremita que falava com o vento. Sem poder articular palavra, o escrivão escreveu a sua pena na terra. O ancião, olhando para ele com compaixão, disse-lhe: "Naum, a tua voz nunca foi tua; era um empréstimo do céu para ser a espada da verdade. Ao negá-la àquele ancião inocente, quebraste o pacto com a criação. A Verdade retirou-se de ti porque tu te retiraste dela quando mais precisava de ti". Naum caiu de joelhos e, pela primeira volta, as suas lágrimas falarono por ele. Compreendeu que a sua mudez não era um castigo, mas o reflexo exacto do vazio que tinha deixado no mundo com a sua cobardia.</p>
                <p class="vi" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Trong tuyệt vọng, Nahum đã đi bộ lên đỉnh Núi Tiếng Vang, nơi có một ẩn sĩ trò chuyện với gió. Không thể thốt ra lời nào, người chép thuê đã viết nỗi đau của mình xuống đất. Vị ẩn sĩ nhìn ông với lòng trắc ẩn và nói: "Nahum, giọng nói của ông chưa bao giờ là của ông cả; đó là một món nợ từ thiên đường để làm thanh kiếm của sự thật. Bằng cách từ chối giúp đỡ ông lão vô tội đó, ông đã phá vỡ giao ước với tạo hóa. Sự Thật đã rút lui khỏi ông vì ông đã rút lui khỏi nó khi nó cần ông nhất". Nahum quỳ rạp xuống và lần đầu tiên, những giọt nước mắt đã nói thay ông. Ông hiểu rằng sự câm lặng của mình không phải là một hình phạt, mà là phản chiếu chính xác khoảng trống mà ông đã để lại trên thế giới bằng sự hèn nhát của mình.</p>"""

    par_p4 = """
                <p class="it" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Nahum passò il resto della sua vita cercando l'anziano esiliato per chiedergli perdono, non con i suoni, ma con atti di servizio. Solo dopo anni passati a proteggere i perseguitati in silenzio, un giorno, difendendo un bambino da un colpo ingiusto, un sussurro rauco ma puro sgorgò dalle sue labbra. Aveva imparato la lezione più sacra del karma: che la voce ha potere solo quando viene usata per illuminare la giustizia, e che il nostro scopo non si compie in ciò che diciamo per brillare, ma in ciò che osiamo dire affinché altri non vivano nell'ombra. Da allora in poi, Nahum parlò meno, ma ogni sua parola era un balsamo che guariva l'anima di chi lo ascoltava.</p>
                <p class="zh" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">那鸿余生都在寻找被流放的老人，请求他的原谅，不是用声音，而是用服务。在默默保护被迫害者多年后，有一天，在保护一个孩子免受不公正打击时，他沙哑但纯净的耳语从嘴唇中流出。他学到了业力最神圣的一课：只有当声音被用来照亮正义时，它才有力量；我们的使命不在于为了闪耀而说的话，而在于我们为了不让别人生活在阴影中而敢于说的话。从那时起，那鸿说话变少了，但他的每一句话都像是一剂良药，治愈着听者的灵魂。</p>
                <p class="ar" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">أمضى ناحوم بقية حياته في البحث عن الشيخ المنفي ليطلب منه المغفرة، ليس بالأصوات، بل بأعمال الخدمة. وبعد سنوات من حماية المضطهدين في صمت، وفي أحد الأيام، أثناء الدفاع عن طفل من ضربة غير عادلة، انطلقت من شفتيه همسة مبحوحة ولكنها نقية. لقد تعلم الدرس الأقدس في الكرمة: أن الصوت لا يمتلك القوة إلا عندما يُستخدم لإنارة العدل، وأن غرضنا لا يتحقق في ما نقوله لنلمع، بل في ما نجرؤ على قوله حتى لا يعيش الآخرون في الظل. ومنذ ذلك الحين، قل كلام ناحوم، لكن كل كلمة منه كانت بلسماً يشفي روح من يسمعه.</p>
                <p class="ru" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Наум провел остаток жизни в поисках изгнанного старика, чтобы попросить у него прощения — не звуками, а делами служения. Лишь спустя годы молчаливой защиты преследуемых, однажды, защищая ребенка от несправедливого удара, из его уст вырвался хриплый, но чистый шепот. Он усвоил самый священный урок кармы: голос имеет силу только тогда, когда он используется для освещения справедливости, и что наша цель исполняется не в том, что мы говорим ради собственного блеска, а в том, что мы осмеливаемся сказать, чтобы другие не жили в тени. С тех пор Наум говорил меньше, но каждое его слово было бальзамом, исцеляющим душу того, кто его слушал.</p>
                <p class="de" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Nahum verbrachte den Rest seines Lebens damit, den verbannten alten Mann zu suchen, um ihn um Vergebung zu bitten – nicht mit Lauten, sondern durch Taten des Dienens. Erst nach Jahren, in denen er die Verfolgten schweigend geschützt hatte, entsprang eines Tages, während er ein Kind vor einem ungerechten Schlag verteidigte, ein heiseres, aber reines Flüstern seinen Lippen. Er hatte die heiligste Lektion des Karma gelernt: dass die Stimme nur Macht hat, wenn sie eingesetzt wird, um die Gerechtigkeit zu erhellen, und dass unsere Bestimmung sich nicht darin erfüllt, was wir sagen, um zu glänzen, sondern in dem, was wir zu sagen wagen, damit andere nicht im Schatten leben. Von da an sprach Nahum weniger, aber jedes seiner Worte war ein Balsam, der die Seele dessen heilte, der ihn hörte.</p>
                <p class="fr" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Nahum passa le reste de sa vie à chercher le vieillard exilé pour lui demander pardon, non avec des sons, mais par des actes de service. Ce n'est qu'après des années passées à protéger les persécutés en silence qu'un jour, en défendant un enfant d'un coup injuste, un murmure enroué mais pur jaillit de ses lèvres. Il avait appris la leçon la plus sacrée du karma : que la voix n'a de pouvoir que lorsqu'elle est utilisée pour éclairer la justice, et que notre mission ne s'accomplit pas dans ce que nous disons pour briller, mais dans ce que nous osons dire pour que d'autres ne vivent pas dans l'ombre. Dès lors, Nahum parla moins, mais chacun de ses mots était un baume qui guérissait l'âme de celui qui l'écoutait.</p>
                <p class="ja" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">ナフムは、音ではなく奉仕の行いを通じて追放された老人に許しを乞うために残りの人生を費やしました。沈黙の中で虐げられた人々を守り続けて数年が経ったある日、不当な暴力から子供を守ろうとした時、かすれているが清らかな囁きが彼の唇から漏れました。彼はカルマの最も神聖な教えを学びました。声は正義を照らすために使われる時のみ力を持つこと、そして私たちの目的は自分が輝くために言うことではなく、他の人々が影の中で生きないようにあえて言うことによって果たされるのだということを。それ以来、ナフムは多くを語りませんでしたが、彼の全ての言葉は、それを聞く者の魂を癒やす香油となりました。</p>
                <p class="pt" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Naum passou o resto da sua vida procurando o ancião desterrado para lhe pedir perdão, não com sons, mas com actos de serviço. Só depois de anos a proteger os perseguidos em silêncio, um dia, ao defender uma criança de um golpe injusto, um sussurro rouco mas puro brotou dos seus lábios. Tinha aprendido a lição mais sagrada do carma: que a voz só tem poder quando é usada para iluminar a justiça, e que o nosso propósito não se cumpre no que dizemos para brilhar, mas no que nos atrevemos a dizer para que outros não vivam na sombra. Desde então, Naum falou menos, ma cada palavra sua era um bálsamo que curava a alma de quem o escutava.</p>
                <p class="vi" style="font-style: italic; color: #ddd; line-height: 1.8; text-align: justify; margin-bottom: 1.5rem;">Nahum đã dành phần đời còn lại để tìm kiếm cụ già bị lưu đày để xin sự tha thứ, không phải bằng âm thanh mà bằng những hành động phụng sự. Chỉ sau nhiều năm âm thầm bảo vệ những người bị đàn áp, một ngày nọ, khi đang bảo vệ một đứa trẻ khỏi một cú đánh bất công, một lời thì thầm khản đặc nhưng thuần khiết đã thốt ra từ môi ông. Ông đã học được bài học thiêng liêng nhất của nghiệp báo: rằng tiếng nói chỉ có sức mạnh khi nó được dùng để làm sáng tỏ công lý, và mục đích của chúng ta không được hoàn thành qua những gì chúng ta nói để tỏa sáng, mà qua những gì chúng ta dám nói để người khác không phải sống trong bóng tối. Kể từ đó, Nahum nói ít hơn, nhưng mỗi lời nói của ông đều là một liều thuốc chữa lành tâm hồn cho bất kỳ ai nghe thấy.</p>"""

    content = content.replace('<p class="it">ToDo</p><p class="zh">ToDo</p><p class="ar">ToDo</p><p class="ru">ToDo</p><p class="de">ToDo</p><p class="fr">ToDo</p><p class="ja">ToDo</p><p class="pt">ToDo</p><p class="vi">ToDo</p>', par_p1 + par_p2 + par_p3 + par_p4)

    # --- MORAL ---
    morals = """<span class="it">Tacere davanti all'ingiustizia è scavare la fossa della propria libertà; la parola è l'arma della luce, usala sempre per difendere la verità.</span>
                <span class="zh">在不公正面前保持沉默是在挖掘你自己自由的坟墓；语言是光明的武器，永远用它来捍卫真理。</span>
                <span class="ar">الصمت أمام الظلم هو حفر قبر حريتك؛ الكلمة هي سلاح النور، استخدمها دائماً للدفاع عن الحق.</span>
                <span class="ru">Молчать перед лицом несправедливости — значит рыть могилу собственной свободе; слово — это оружие света, всегда используйте его для защиты истины.</span>
                <span class="de">Angesichts von Ungerechtigkeit zu schweigen bedeutet, das Grab der eigenen Freiheit zu schaufeln; das Wort ist die Waffe des Lichts, setze es immer ein, um die Wahrheit zu verteidigen.</span>
                <span class="fr">Se taire devant l'injustice, c'est creuser la tombe de sa propre liberté ; la parole est l'arme de la lumière, utilisez-la toujours pour défendre la vérité.</span>
                <span class="ja">不公正を前に沈黙することは、自らの自由の墓を掘ることである。言葉は光の武器であり、常に真実を守るために使いなさい。</span>
                <span class="pt">Calar perante a injustiça é cavar a sepultura da tua própria liberdade; a palavra é a arma da luz, usa-a sempre para defender a verdade.</span>
                <span class="vi">Im lặng trước bất công là đang tự đào mồ chôn sự tự do của chính mình; lời nói là vũ khí của ánh sáng, hãy luôn sử dụng nó để bảo vệ sự thật.</span>"""
    
    content = content.replace('<span class="it">ToDo</span><span class="zh">ToDo</span><span class="ar">ToDo</span><span class="ru">ToDo</span><span class="de">ToDo</span><span class="fr">ToDo</span><span class="ja">ToDo</span><span class="pt">ToDo</span><span class="vi">ToDo</span>', morals)

    # --- ORIGINAL INSPIRATION TITLES ---
    # These titles are also in ToDo sometimes or ES/EN only
    # Let's check if they need translation. In the template they were:
    # <h3 class="es" ...>La Inspiración Original</h3>
    # <h3 class="en" ...>The Original Inspiration</h3>
    # I should add others if I want perfection, but let's see.
    # The template only has ES/EN. Let's add the others for consistency.
    
    insp_titles = """<h3 class="es" style="color: var(--gold); text-align: center; margin-bottom: 2rem; font-family: 'Cinzel', serif;">La Inspiración Original</h3>
                <h3 class="en" style="color: var(--gold); text-align: center; margin-bottom: 2rem; font-family: 'Cinzel', serif;">The Original Inspiration</h3>
                <h3 class="it" style="color: var(--gold); text-align: center; margin-bottom: 2rem; font-family: 'Cinzel', serif;">L'Ispirazione Originale</h3>
                <h3 class="zh" style="color: var(--gold); text-align: center; margin-bottom: 2rem; font-family: 'Cinzel', serif;">原始灵感</h3>
                <h3 class="ar" style="color: var(--gold); text-align: center; margin-bottom: 2rem; font-family: 'Cinzel', serif;">الإلهام الأصلي</h3>
                <h3 class="ru" style="color: var(--gold); text-align: center; margin-bottom: 2rem; font-family: 'Cinzel', serif;">Оригинальное вдохновение</h3>
                <h3 class="de" style="color: var(--gold); text-align: center; margin-bottom: 2rem; font-family: 'Cinzel', serif;">Die ursprüngliche Inspiration</h3>
                <h3 class="fr" style="color: var(--gold); text-align: center; margin-bottom: 2rem; font-family: 'Cinzel', serif;">L'Inspiration Originale</h3>
                <h3 class="ja" style="color: var(--gold); text-align: center; margin-bottom: 2rem; font-family: 'Cinzel', serif;">オリジナルのインスピレーション</h3>
                <h3 class="pt" style="color: var(--gold); text-align: center; margin-bottom: 2rem; font-family: 'Cinzel', serif;">A Inspiração Original</h3>
                <h3 class="vi" style="color: var(--gold); text-align: center; margin-bottom: 2rem; font-family: 'Cinzel', serif;">Nguồn Cảm Hứng Gốc</h3>"""
    
    content = content.replace('<h3 class="es" style="color: var(--gold); text-align: center; margin-bottom: 2rem; font-family: \'Cinzel\', serif;">La Inspiración Original</h3>\n                <h3 class="en" style="color: var(--gold); text-align: center; margin-bottom: 2rem; font-family: \'Cinzel\', serif;">The Original Inspiration</h3>', insp_titles)

    with open(target, 'w', encoding='utf-8') as f:
        f.write(content)
    print("Injection complete for Chapter 63.")

if __name__ == "__main__":
    fix_ch63()
